import { useState } from "react";

export const tasks = [
  { title: "3 Consumer Product Briefs", type: "project", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm"], status: "not-started", desc: "Product concepts for claude.ai with user problem, solution, validation plan", priority: "high" },
  { title: "Consumer Product MVP", type: "project", roles: ["anthropic-consumer-pm", "anthropic-ui-engineer"], status: "not-started", desc: "Prototype your best product concept with Claude Code", priority: "high" },
  { title: "Competitive Analysis Doc", type: "project", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm"], status: "not-started", desc: "ChatGPT vs Gemini vs Copilot vs Claude feature comparison", priority: "medium" },
  { title: "Consumer Growth Strategy", type: "project", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm"], status: "not-started", desc: "Strategy to 5x Claude consumer market share in 12 months", priority: "medium" },
  { title: "Anthropic Product Philosophy", type: "learning", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm", "anthropic-people-products"], status: "not-started", desc: "Cat Wu's posts, side quests, Labs announcement, product culture", priority: "high", hours: 4 },
  { title: "Consumer AI Competitive Landscape", type: "learning", roles: ["anthropic-consumer-pm"], status: "not-started", desc: "Use ChatGPT, Gemini, Copilot, Perplexity for a full day each", priority: "high", hours: 6 },
  { title: "Success Metrics Frameworks", type: "learning", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm"], status: "not-started", desc: "HEART, AARRR, North Star metric — practice on Claude features", priority: "medium", hours: 4 },
  { title: "Anthropic Research (PM Level)", type: "learning", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm"], status: "not-started", desc: "Constitutional AI, scaling laws, extended thinking — what they mean for products", priority: "medium", hours: 4 },
  { title: "Anthropic Interview Process", type: "learning", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm", "anthropic-people-products", "anthropic-ui-engineer"], status: "not-started", desc: "Interview format, culture fit, mission alignment, coding rounds", priority: "high", hours: 4 },
  { title: "Mock Interview Practice", type: "learning", roles: ["anthropic-consumer-pm", "anthropic-claude-code-pm", "anthropic-people-products"], status: "not-started", desc: "Product sense, metrics, strategy, behavioral — 3 full mock loops", priority: "high", hours: 8 },
];

export const meta = {
  id: "anthropic-consumer-pm",
  company: "Anthropic",
  title: "Product Manager, Consumer",
  comp: "$385K–$460K",
  fit: "95%",
  priority: 1,
  status: "prep",
  loc: "SF / NYC",
  tags: ["PM","Consumer","Founder-fit","0-to-1"],
  color: "#10b981",
  strengths: ["Former consumer founder","Prototypes with Claude daily","0-to-1 DNA","Deep technical background","Obsessed with craft","IS the target user"],
  gaps: [{g:"No formal PM title",s:"MEDIUM"},{g:"Consumer distribution at scale",s:"MEDIUM"},{g:"Research-to-product translation",s:"LOW"},{g:"SF/NYC location",s:"VARIES"}],
  verdict: "They want a founder. You are one. Top priority.",
};

const S = [
  { id:"opp", title:"The Opportunity", icon:"◆", type:"opp", data:{
    role:"Product Manager, Consumer", comp:"$385K–$460K + equity", team:"Consumer Team (under Ami Vora, Head of Product; previously Mike Krieger CPO)", loc:"San Francisco, CA | New York City, NY",
    focus:"Lead 0-to-1 product development for claude.ai consumer experiences. Identify nascent research capabilities → transform them into products millions of people use. They explicitly want a 'former consumer founder.'",
    whyNow:"Claude has ~30M monthly active users but only 3-4% of the US AI chatbot market vs ChatGPT's 68%. Anthropic's enterprise business is 80% of revenue — the consumer side is the growth lever they need to pull. They just launched Anthropic Labs (Mike Krieger leading experimental products). Cat Wu (Claude Code PM) revealed they've abandoned long-term roadmaps for 'side quests' — rapid experimentation. They need founders who can prototype-to-product in days, not quarters. This is one of the highest-comp PM roles in tech right now.",
    status:"Active on Greenhouse. Extremely competitive — they explicitly want founder-types. But the comp ($385K-$460K) signals how seriously they're taking this hire.",
    verdict:"This is your best shot at Anthropic. Better than People Products EM, better than UI Engineer. Here's why: they literally say they want 'a former consumer founder who deeply understands what makes experiences intuitive and indispensable.' You're a former consumer founder (NexusWealth, Hostr). You prototype with Claude Code. You build AI-native products. You're obsessed with craft. This posting reads like they wrote it for you.",
  }},
  { id:"intel", title:"Company Intel", icon:"◇", type:"intel", data:{
    news:[
      {e:"Consumer growth imperative", d:"~30M MAU but only 3-4% US market share vs ChatGPT's 68%. Enterprise is 80% of $14B annualized revenue. Consumer is the growth frontier — and the lead-gen engine for enterprise."},
      {e:"Anthropic Labs launched", d:"Mike Krieger (Instagram co-founder) moved from CPO to lead Labs — an incubator for experimental products. Ami Vora now leads Product org. Labs culture: ship fast, experiment wildly, kill what doesn't work."},
      {e:"'Side quests' replace roadmaps", d:"Cat Wu (Claude Code PM) revealed Anthropic has abandoned long-term roadmaps. Teams run short experiments where anyone can prototype. Claude Code, AskUserQuestion tool, and todo lists all emerged from informal experiments, not planned roadmap items."},
      {e:"Super Bowl campaign impact", d:"Feb 2026 Super Bowl ad generated 69K+ Claude mentions on X, penetrating 2x deeper relative to brand size than OpenAI's spots. Consumer awareness is ramping."},
      {e:"Product velocity is insane", d:"Claude Code: research preview → $2.5B ARR in ~12 months. Cowork: announced → enterprise launch in 6 weeks. Skills, Chrome extension, artifacts, inline charts — all shipped in rapid succession."},
      {e:"Model capabilities are the product moat", d:"Opus 4.6: 1M token context, 12-hour task completion, Agent Teams. Sonnet 4.6: 72.5% on OSWorld. The consumer PM's job is to turn these capabilities into products people love."},
    ],
    culture:[
      {name:"Prototype before documenting", desc:"Write a spec, then send it to Claude Code and see what comes back before investing in detailed plans."},
      {name:"Keep implementations simple", desc:"Complex workarounds for model limitations become unnecessary baggage when the next model drops. Anthropic cut 20% of system prompting with Opus 4.6."},
      {name:"Side quests > roadmaps", desc:"Short, self-directed experiments where anyone can prototype. Popular features emerged from informal experiments."},
      {name:"'You're building on ground that's rising underneath you'", desc:"What's technologically possible at the start of a project no longer predicts what's possible at the end. Traditional PM playbooks don't work."},
    ],
  }},
  { id:"fit", title:"Fit Analysis", icon:"△", type:"fit", data:{
    strengths:[
      "Former consumer founder — NexusWealth (fintech) and Hostr (marketplace). The posting literally asks for 'a former consumer founder.' This is your headline qualification.",
      "You prototype with AI tools daily — you build skills, artifacts, and complex workflows with Claude. The posting asks candidates to 'prototype with AI tools like Claude Code.' You don't just use them, you push them to their limits.",
      "0-to-1 product development DNA — you've launched products from scratch at two startups. You know what product-market fit feels like and how to find it cheaply.",
      "Deep technical background as an EM — you can work cross-functionally with engineering because you've LED engineering teams. You don't just speak technical, you think technical.",
      "Obsessed with craft — the Vision Quest newsletter, the custom Claude skills, the polished artifacts in this conversation. Everything you build has attention to detail and quality.",
      "Can't stop thinking about new AI products — you're literally having Claude build you career intelligence tools in real-time. You see capability → product opportunities constantly.",
      "You ARE the consumer — you use claude.ai daily, across mobile and web, and have strong opinions about what works and what should be better.",
    ],
    adjacent:[
      "EM → PM: You've been managing engineers, not shipping as a PM. But founder experience + EM technical depth = a PM who can prototype AND lead execution. Frame this as an advantage, not a gap.",
      "Meta experience adds scale context: You know what it takes to ship at a company with billions of users. Anthropic's consumer product serves 30M — you bring the playbook for what comes next.",
      "Your newsletter (Vision Quest) is content product thinking — you curate, synthesize, and deliver value to an audience weekly. That's consumer product instinct.",
    ],
    gaps:[
      {gap:"No formal PM title on resume", critical:"MEDIUM", note:"You've been CTO (which includes product) and EM (which includes product decisions). The posting says '8+ years in product management' OR 'track record as a founder.' Your founder track record is the path here.", time:"Narrative reframing"},
      {gap:"Consumer product distribution/growth experience", critical:"MEDIUM", note:"'Experience launching ambitious consumer products that have found distribution or commercial success.' Your startups were real but not massive scale. Pair your startup experience with your Meta scale context.", time:"Narrative prep"},
      {gap:"Research-to-product translation", critical:"LOW", note:"'Work with researchers to understand what's emerging and what it means for users.' You haven't worked with ML researchers directly, but your deep AI tool usage means you intuitively understand capability → product mapping.", time:"2 weeks study"},
      {gap:"SF or NYC location", critical:"VARIES", note:"This role is NOT listed as remote — it's SF or NYC. You're in Boca Raton. This could be a dealbreaker or negotiable. Anthropic says they support relocation and can be flexible during transition.", time:"Logistics"},
    ],
  }},
  { id:"knowledge", title:"Knowledge Map", icon:"▽", type:"knowledge", data:[
    {name:"Anthropic Product Philosophy", topics:["'Side quests' over roadmaps — short experiments, rapid prototyping, kill what doesn't work","Prototype before documenting — build with Claude Code, then decide if it's worth speccing","Model capabilities change mid-project — 'building on ground that's rising underneath you'","Consumer as enterprise lead-gen — every consumer user is a potential enterprise advocate","Safety as differentiator — Constitutional AI, reliability, and trust as competitive moats vs ChatGPT"], ai:"Read Cat Wu's post on AI product management. Study how Claude Code, Cowork, and Skills each went from experiment to product. Ask Claude to help you map Anthropic's product philosophy to your own founder experience."},
    {name:"Claude Consumer Product Surface", topics:["Chat: core interaction model, streaming, extended thinking, tool use","Artifacts: inline rendering of code, documents, visualizations","Projects: persistent context, custom instructions, knowledge files","Skills: SKILL.md ecosystem, auto-triggering, progressive disclosure","Connectors: MCP-based integrations with Google Drive, Gmail, Slack, Figma","Memory: cross-conversation context, user preferences","Cowork: agentic desktop automation, plugins, sub-agents","Claude Code: terminal-based coding agent, remote control from mobile"], ai:"You already know most of this. Go deeper: study the features you DON'T use regularly. Think about what's missing. Prepare 3-5 product ideas for new consumer features."},
    {name:"Consumer AI Competitive Landscape", topics:["ChatGPT: 68% market share, voice mode, memory, GPT Store, Canvas, image generation","Google Gemini: 18% market share, deep Google integration, multimodal, long context","Microsoft Copilot: enterprise distribution through M365, consumer Copilot app","Perplexity: search-first AI, citations, Pro tier","Character.ai, Pi, Poe: personality-first, social, aggregator models","Where Claude wins: coding, long-form reasoning, safety, enterprise trust. Where it loses: consumer awareness, voice, image generation, mobile experience"], ai:"Use Claude to build a competitive analysis matrix. For each competitor, identify: core user persona, key differentiator, biggest weakness, what Anthropic should learn from them."},
    {name:"0-to-1 AI Product Development", topics:["Capability scouting: translating research papers into product opportunities","Rapid prototyping: Claude Code for MVPs, user testing with internal dogfooding","Product-market fit signals for AI products: retention vs novelty, task completion vs engagement","Success metrics for AI consumer products: HEART framework, task success rate, time-to-value","The 'uncanny valley' of AI products: when something is almost useful but not quite","Distribution for AI products: word-of-mouth, content loops, 'show don't tell' demos"], ai:"Practice the full cycle: pick a Claude capability, identify a user need, prototype a solution, define success metrics, and write a 1-page product brief. Do this 3 times with different capabilities."},
    {name:"Anthropic Research (Consumer PM Level)", topics:["Constitutional AI: how it works, why it matters for consumer trust","Scaling laws: why bigger models = better products (and the limits)","Extended thinking: chain-of-thought reasoning, when to show vs hide it","Tool use: how Claude calls external tools, MCP protocol","Multimodal capabilities: vision, document understanding, code execution","Safety research: RLHF, red-teaming, responsible deployment"], ai:"You don't need to understand the math. You need to understand what each research direction MEANS for products. Ask Claude: 'What consumer product could I build if [research capability] improved 10x?'"},
    {name:"Interview Prep: Anthropic Consumer PM", topics:["Product sense: 'Design a new consumer feature for claude.ai' — show taste and craft","Metrics: HEART/AARRR frameworks, 'How would you measure success for Claude artifacts?'","Strategy: 'How should Anthropic grow consumer share from 3% to 15%?'","Execution: 'How would you take a research capability from paper to shipped product in 2 weeks?'","Mission: 'Why Anthropic? Why consumer? What's your vision for AI improving daily life?'","Founder stories: 'Tell me about building NexusWealth/Hostr. What did you learn about PMF?'"], ai:"Run mock interviews with Claude playing a senior Anthropic consumer PM. Practice product sense questions especially — these are make-or-break at Anthropic."},
  ]},
  { id:"plan", title:"30-Day Sprint", icon:"⬡", type:"plan", data:[
    {week:"Week 1: Product Ideas + Portfolio", days:[
      {day:"Days 1-2", focus:"Build 3 Consumer Product Concepts", tasks:["Brainstorm 10 new consumer features for claude.ai based on current model capabilities","Narrow to 3 strongest ideas. For each: user problem, proposed solution, why now, how to validate","Write a 1-page product brief for each using Claude as a thinking partner","Make them opinionated and creative — this is your 'founder brain' showcase"], hrs:"4-5 hrs/day"},
      {day:"Days 3-4", focus:"Prototype Your Best Idea", tasks:["Pick your strongest product concept and build an MVP with Claude Code","Deploy it. Make it real enough that someone could use it and give feedback","Document your process: how you went from idea to working prototype in 2 days","This IS the interview. Anthropic wants founders who can do this."], hrs:"4-5 hrs/day"},
      {day:"Days 5-6", focus:"Competitive Deep Dive", tasks:["Use every AI consumer product for a full day each: ChatGPT, Gemini, Copilot, Perplexity","Document what each does better than Claude, and what Claude does better","Identify 3 features Claude should steal and 3 features that are uniquely Anthropic","Write a competitive analysis doc you could present in an interview"], hrs:"3-4 hrs/day"},
      {day:"Day 7", focus:"Synthesis", tasks:["Compile: 3 product briefs + 1 working prototype + competitive analysis","This is your 'portfolio' for the application — tangible evidence of founder-PM thinking"], hrs:"2-3 hrs"},
    ]},
    {week:"Week 2: Anthropic Deep Dive + Metrics", days:[
      {day:"Days 8-9", focus:"Study Anthropic's Product Culture", tasks:["Read Cat Wu's post on AI product management in detail","Study how each major feature shipped: Claude Code, Cowork, Skills, Artifacts","Read Anthropic's research blog — focus on what each paper MEANS for products, not the math","Read 'Introducing Anthropic Labs' announcement — understand the new org structure"], hrs:"3-4 hrs/day"},
      {day:"Days 10-11", focus:"Success Metrics Practice", tasks:["Define HEART metrics for: claude.ai chat, Artifacts, Skills, Cowork","Practice: 'How would you measure success for a new Claude consumer feature?'","Study the metrics framework failures from the Anthropic PM interview post (Aakash Gupta's article)","Build a metrics dashboard concept for Claude consumer engagement"], hrs:"3-4 hrs/day"},
      {day:"Days 12-13", focus:"Consumer Growth Strategy", tasks:["Analyze: how does Anthropic go from 3% to 15% consumer market share?","Study distribution channels: word-of-mouth, content loops, partnerships, SEO/SEM","Look at how Claude Code grew to $2.5B ARR — what's the consumer equivalent?","Write a 'Claude Consumer Growth Strategy' doc — this could be your interview capstone"], hrs:"3-4 hrs/day"},
      {day:"Day 14", focus:"Synthesis", tasks:["Refine all materials. Practice presenting your product ideas and growth strategy.","Update your competitive analysis with any new insights."], hrs:"2-3 hrs"},
    ]},
    {week:"Week 3: Narrative + Interview Prep", days:[
      {day:"Days 15-16", focus:"Founder Narrative", tasks:["Craft your story: 'I've built consumer products from zero. I've led engineering teams at Meta. I prototype with Claude every day. I'm the intersection of founder instinct, technical depth, and AI-native product thinking.'","Prepare NexusWealth and Hostr stories as case studies in 0-to-1 development","Document lessons learned: what worked, what failed, what you'd do differently","Connect each lesson to how you'd approach consumer PM at Anthropic"], hrs:"3-4 hrs/day"},
      {day:"Days 17-18", focus:"Product Sense Practice", tasks:["Practice 10 product sense questions: 'Design a feature for...' 'How would you improve...'","Focus on taste, craft, and opinion — Anthropic wants opinionated PMs, not frameworks robots","Practice: 'How would you take extended thinking and turn it into a consumer feature people love?'","Practice: 'What's the biggest missed opportunity in claude.ai right now?'"], hrs:"3-4 hrs/day"},
      {day:"Days 19-21", focus:"Full Mock Interviews", tasks:["Mock 1: Product sense + metrics (Claude as interviewer)","Mock 2: Strategy + execution (Claude as interviewer)","Mock 3: Founder stories + mission alignment (Claude as interviewer)","Get feedback, refine weak areas, tighten your narratives"], hrs:"3-4 hrs/day"},
    ]},
    {week:"Week 4: Apply + Network", days:[
      {day:"Days 22-25", focus:"Application Materials", tasks:["Resume rewrite: lead with founder experience, then Meta, then AI product building","Cover letter: your vision for claude.ai consumer product + why you're the founder-PM they need","Include links to: your prototype, product briefs, growth strategy doc","Make it impossible to ignore — this application should feel like a product pitch"], hrs:"3-4 hrs/day"},
      {day:"Days 26-30", focus:"Submit + Warm Outreach", tasks:["Submit application","Reach out to Anthropic consumer PMs, Labs team members, Cat Wu's network on LinkedIn/X","Share your product thinking publicly — tweet about Claude features, write about AI product development","Your application should arrive alongside a trail of public signal that you're the right person"], hrs:"2-3 hrs/day"},
    ]},
  ]},
  { id:"tactics", title:"AI Tactics", icon:"□", type:"tactics", data:[
    {name:"Claude as Product Co-founder", desc:"Use Claude as your thinking partner for product ideation. Brainstorm, critique, iterate on consumer feature ideas.", ex:"I'm applying for Consumer PM at Anthropic. Help me brainstorm 10 new consumer features for claude.ai that leverage current model capabilities. For each: what's the user problem, what's the solution, and why would people tell their friends about it? Be creative — think like a founder, not a product framework."},
    {name:"Claude Code as Prototyping Engine", desc:"Build working MVPs of your product ideas. This is literally what the role requires.", ex:"I have a product concept: [describe idea]. Help me build a working MVP using Claude Code. I want something I can show to a user in 2 hours. What's the fastest path to something real and testable?"},
    {name:"Claude as Interview Coach", desc:"Practice Anthropic-specific PM interview questions with real-time feedback.", ex:"You're a senior consumer PM at Anthropic interviewing me for the Consumer PM role. Ask me a product sense question about claude.ai. After I answer, give me honest feedback on: (1) did I show taste and craft, (2) was I opinionated enough, (3) would you hire me based on that answer? Be tough."},
    {name:"Claude as Strategy Analyst", desc:"Develop your consumer growth strategy with rigorous analysis.", ex:"Anthropic's claude.ai has ~30M MAU but only 3-4% of the US AI chatbot market vs ChatGPT's 68%. If you were Consumer PM, what's your strategy to 5x consumer share in 12 months? Consider: distribution channels, product differentiation, pricing, partnerships, and content loops. Be specific and opinionated."},
    {name:"Claude as Research Translator", desc:"Practice turning research capabilities into product ideas — the core skill of this role.", ex:"I just read about [specific Anthropic research]. As a consumer PM, how would I turn this into a product feature? Walk me through: what's the capability, who benefits, what's the MVP, how do we test it, and what does success look like?"},
  ]},
  { id:"res", title:"Resources", icon:"◈", type:"res", data:[
    {cat:"Must Read", items:["Cat Wu's post on AI product management and 'side quests' approach","Anthropic Labs announcement (anthropic.com/news)","Anthropic's research blog — scan for consumer-relevant capabilities","Aakash Gupta's post on Anthropic PM interview metrics question","Anthropic careers page — values, interview process, culture"]},
    {cat:"Product Analysis", items:["Use ChatGPT, Gemini, Copilot, Perplexity daily for competitive understanding","Study claude.ai feature launches: Skills, Cowork, Artifacts, inline charts","Anthropic company analysis reports (for consumer market share data)","METR research on AI capability growth (cited by Cat Wu)"]},
    {cat:"Interview Prep", items:["Exponent Anthropic PM interview guide","Product Manager interview frameworks: HEART, AARRR, North Star metric","0-to-1 product development case studies","Consumer product growth strategy frameworks","Practice: define success metrics for 5 different AI products"]},
    {cat:"Build With", items:["Claude Code — prototype your product ideas","Vercel — deploy your prototypes","Anthropic TypeScript SDK — build working demos","Your own claude.ai usage — document pain points and feature ideas daily"]},
  ]},
];

const Badge = ({color,children}) => {
  const c = {green:"bg-emerald-500/15 text-emerald-300 border-emerald-500/30",amber:"bg-amber-500/15 text-amber-300 border-amber-500/30",red:"bg-red-500/15 text-red-300 border-red-500/30",blue:"bg-blue-500/15 text-blue-300 border-blue-500/30",gray:"bg-gray-500/15 text-gray-300 border-gray-500/30"};
  return <span className={`text-xs px-2 py-0.5 rounded-full border font-mono ${c[color]}`}>{children}</span>;
};
const Opp = ({d}) => (<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[["ROLE",d.role],["COMP",d.comp],["TEAM",d.team],["LOCATION",d.loc]].map(([l,v])=><div key={l} className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">{l}</div><div className="text-white text-sm">{v}</div></div>)}</div><div className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">FOCUS</div><div className="text-white text-sm">{d.focus}</div></div><div className="bg-emerald-900/20 border border-emerald-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">WHY NOW</div><div className="text-emerald-200 text-sm leading-relaxed">{d.whyNow}</div></div><div className="bg-amber-900/20 border border-amber-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">STATUS</div><div className="text-amber-200 text-sm">{d.status}</div></div><div className="bg-emerald-900/30 border border-emerald-400/40 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-300 mb-1.5 font-mono">BOTTOM LINE</div><div className="text-emerald-100 text-sm font-medium">{d.verdict}</div></div></div>);
const Intel = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">WHAT'S HAPPENING</div>{d.news.map((n,i)=><div key={i} className="bg-white/5 border border-white/10 rounded-lg p-3 mb-2"><div className="text-white text-sm font-medium mb-1">{n.e}</div><div className="text-gray-400 text-sm">{n.d}</div></div>)}</div><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">HOW THEY BUILD (CULTURE)</div>{d.culture.map((c,i)=><div key={i} className="bg-blue-900/15 border border-blue-500/20 rounded-lg p-3 mb-2"><div className="text-blue-300 text-sm font-medium mb-1">"{c.name}"</div><div className="text-gray-400 text-sm">{c.desc}</div></div>)}</div></div>);
const FitView = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">WHY YOU — THIS POSTING WAS WRITTEN FOR FOUNDERS LIKE YOU</div>{d.strengths.map((s,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-emerald-400 mt-0.5 text-xs">✓</span><span className="text-gray-300 text-sm">{s}</span></div>)}</div><div><div className="text-xs tracking-widest text-blue-400 mb-3 font-mono">REFRAME THESE</div>{d.adjacent.map((a,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-blue-400 mt-0.5 text-xs">↗</span><span className="text-gray-300 text-sm">{a}</span></div>)}</div><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">GAPS (ALL MANAGEABLE)</div>{d.gaps.map((g,i)=><div key={i} className="border border-white/10 rounded-lg p-3 mb-2"><div className="flex items-center gap-2 mb-1"><span className="text-white text-sm font-medium">{g.gap}</span><Badge color={g.critical==="LOW"?"green":"amber"}>{g.critical}</Badge></div><p className="text-gray-400 text-sm">{g.note}</p><div className="text-xs text-gray-600 font-mono mt-1">Close in: {g.time}</div></div>)}</div></div>);
const KMap = ({d}) => {const [exp,setExp]=useState(null);return <div className="space-y-2">{d.map((k,i)=><div key={i} className="border border-white/10 rounded-lg overflow-hidden"><button onClick={()=>setExp(exp===i?null:i)} className="w-full text-left p-4 flex items-center justify-between hover:bg-white/5 transition-colors"><span className="text-white font-medium text-sm">{k.name}</span><span className="text-gray-500">{exp===i?"−":"+"}</span></button>{exp===i&&<div className="px-4 pb-4 border-t border-white/5"><div className="mt-3 space-y-1.5">{k.topics.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-amber-400 mt-1 text-xs">›</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div><div className="mt-3 bg-blue-900/20 border border-blue-500/20 rounded-lg p-3"><div className="text-xs tracking-widest text-blue-400 mb-1 font-mono">AI ACCELERATION</div><p className="text-blue-200 text-sm">{k.ai}</p></div></div>}</div>)}</div>};
const Plan = ({d}) => {const [aw,setAw]=useState(0);const w=d[aw];return <div><div className="flex gap-2 mb-4 overflow-x-auto">{d.map((_,i)=><button key={i} onClick={()=>setAw(i)} className={`px-3 py-1.5 rounded-lg text-xs font-mono whitespace-nowrap transition-all ${aw===i?"bg-amber-500/20 text-amber-300 border border-amber-500/40":"bg-white/5 text-gray-400 border border-white/10"}`}>Wk {i+1}</button>)}</div><h4 className="text-white font-medium mb-4">{w.week}</h4><div className="space-y-4">{w.days.map((d,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="flex items-center justify-between mb-3"><div><span className="text-amber-400 font-mono text-xs">{d.day}</span><span className="text-gray-500 mx-2">·</span><span className="text-white text-sm font-medium">{d.focus}</span></div><span className="text-gray-600 text-xs font-mono">{d.hrs}</span></div><div className="space-y-1.5">{d.tasks.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-gray-600 mt-0.5 text-xs font-mono">{String(j+1).padStart(2,"0")}</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div></div>)}</div></div>};
const Tactics = ({d}) => <div className="space-y-4">{d.map((t,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="text-white font-medium text-sm mb-1">{t.name}</div><p className="text-gray-400 text-sm mb-3">{t.desc}</p><div className="bg-gray-900 rounded-lg p-3 border border-white/5"><div className="text-xs text-gray-600 font-mono mb-1">PROMPT</div><p className="text-amber-300 text-sm italic">"{t.ex}"</p></div></div>)}</div>;
const Res = ({d}) => <div className="space-y-6">{d.map((c,i)=><div key={i}><div className="text-xs tracking-widest text-amber-400 mb-2 font-mono">{c.cat.toUpperCase()}</div>{c.items.map((item,j)=><div key={j} className="flex items-start gap-2 mb-1"><span className="text-gray-600 mt-0.5 text-xs">›</span><span className="text-gray-300 text-sm">{item}</span></div>)}</div>)}</div>;
const R = {opp:Opp,intel:Intel,fit:FitView,knowledge:KMap,plan:Plan,tactics:Tactics,res:Res};

export default function Brief() {
  const [a,setA] = useState("opp");
  const s = S.find(x=>x.id===a);
  const V = R[s.type];
  return (
    <div className="min-h-screen text-white" style={{background:"linear-gradient(160deg,#090909 0%,#0f0f0f 50%,#0a0a0a 100%)",fontFamily:"'IBM Plex Sans',sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap');.font-mono{font-family:'IBM Plex Mono',monospace}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.1);border-radius:2px}`}</style>
      <div className="border-b border-white/10 px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-3"><div className="w-2 h-2 bg-emerald-400 rounded-full animate-pulse"/><span className="text-xs font-mono text-gray-500 tracking-widest">JOB PREP INTELLIGENCE BRIEF — TOP PRIORITY</span></div><h1 className="text-2xl md:text-3xl font-light text-white mb-2" style={{letterSpacing:"-0.02em"}}>Anthropic · Consumer PM</h1><p className="text-gray-500 text-sm">They're looking for a founder. You are one. $385K-$460K. Apply immediately.</p></div></div>
      <div className="border-b border-white/10 px-6 py-3 sticky top-0 z-10" style={{background:"rgba(9,9,9,0.95)",backdropFilter:"blur(12px)"}}><div className="max-w-4xl mx-auto flex gap-1 overflow-x-auto">{S.map(x=><button key={x.id} onClick={()=>setA(x.id)} className={`px-3 py-1.5 rounded-md text-xs font-mono whitespace-nowrap transition-all ${a===x.id?"bg-white/10 text-white":"text-gray-600 hover:text-gray-400"}`}><span className="mr-1.5">{x.icon}</span>{x.title}</button>)}</div></div>
      <div className="px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-6"><span className="text-amber-400 text-lg">{s.icon}</span><h2 className="text-xl font-light text-white">{s.title}</h2></div><V d={s.data}/></div></div>
      <div className="border-t border-white/5 px-6 py-4"><div className="max-w-4xl mx-auto text-center"><p className="text-gray-700 text-xs font-mono">~90 hrs over 30 days · founder energy + portfolio approach · prototype everything</p></div></div>
    </div>
  );
}
