import { useState } from "react";

const S = [
  { id:"opp", title:"The Opportunity", icon:"◆", type:"opp", data:{
    role:"Product Manager — Games Discovery", comp:"$440K–$725K (salary + you choose stock/cash split)", team:"Product Merchandising → New Content Exploration (NCE)", loc:"USA — Remote (PST hours, occasional CA travel)",
    focus:"Own the product strategy for how Netflix members discover and engage with games. Define discovery experiences, features, and capabilities across TV, mobile, tablet, and web. Sit at the intersection of Product, Tech, and Games Studio — the connective tissue ensuring the product surface evolves with content strategy. Also shape how games fit alongside Live, Podcasts, and other emerging content types on a unified platform.",
    whyNow:"Netflix is making a massive strategic pivot: cloud-first gaming with TV as the priority platform. Co-CEO Greg Peters called it a 'big priority' for 2026. The games library has 93+ titles across mobile and cloud. Party games on TV (Boggle, Pictionary, LEGO Party) drove a significant engagement uptick — 10% reach among eligible members off a small base. FIFA football game designed for TV is coming. Warner Bros. Discovery acquisition would bring Mortal Kombat, DC games. The $140B gaming market (ex-China) is 'just scratching the surface.' This PM role shapes how 300M+ subscribers discover and play games — it's a 0-to-1 product category on a massive platform.",
    status:"Active (posted Mar 25, 2026). JR39646. Product Management team, Streaming business unit. Remote with PST hours required.",
    verdict:"This is a fascinating opportunity with a very specific and somewhat narrow fit requirement: '7+ years of experience developing consumer products AND experience working on games streaming products at scale.' The games streaming experience requirement is the critical question. You haven't worked on games streaming products specifically. However, your consumer product experience is strong (fuboTV streaming, Quest OS, founder projects), and your understanding of content discovery on TV platforms is deep. The comp ceiling ($725K) is the highest of any role on your list. The strategic importance is massive — Netflix is betting that games become a core pillar alongside film, series, and live events. If you can make a compelling case that your TV platform discovery experience + founder DNA + consumer product instincts = the right person to shape games discovery on Netflix, this could be extraordinary.",
  }},
  { id:"intel", title:"Company & Games Intel", icon:"◇", type:"intel", data:{
    news:[
      {e:"Cloud-first gaming strategy (Q4 2025 earnings)", d:"Netflix is pivoting from mobile-first to cloud-first gaming. TV-based play is the priority. Phone-as-controller model for living room games. Cloud games stream directly to TV — no downloads."},
      {e:"93+ games across mobile and cloud (Feb 2026)", d:"82+ mobile games on iOS/Android, expanding cloud catalog. Genres: action, puzzle, strategy, RPG, party, sports. Mix of Netflix IP (Stranger Things, Narcos, Queen's Gambit) and licensed titles (GTA, Red Dead Redemption)."},
      {e:"Party games driving TV engagement", d:"Boggle, Pictionary, LEGO Party launched as cloud games on TV. ~10% reach among eligible members. 'Significant engagement uptick.' Phone-as-controller enables family game night."},
      {e:"FIFA football game for TV (2026)", d:"Newly reimagined FIFA simulation game designed specifically for TV play. Developed by Delphi Interactive. Signals commitment to cloud gaming on big screens."},
      {e:"Warner Bros. Discovery potential acquisition", d:"If completed, Netflix gains Mortal Kombat, DC titles, and experienced game studios. Major IP expansion for the games catalog."},
      {e:"$140B market opportunity", d:"Gaming is ~$140B global consumer spend (ex-China/Russia). Netflix framing games as engagement/retention driver, not revenue driver — extending time on platform."},
      {e:"Games discovery is a known gap", d:"Games currently appear as a tab in the Netflix app. Discovery of games within the app has been cited as a challenge — members don't know games exist or how to find them. Kids' profiles recently added game visibility. This role exists to solve this problem."},
      {e:"North star metric: engagement", d:"Netflix Games president Alain Tascan confirmed engagement (not revenue) is the north star. Games extend member engagement with the platform and reinforce content flywheel."},
    ],
    stack:[
      {name:"Discovery/Browse UX", role:"How members find games across TV, mobile, tablet, web", rel:"Core — you own this"},
      {name:"Cross-platform surfaces", role:"TV (cloud), mobile (download), browser — unified discovery", rel:"Core challenge"},
      {name:"A/B testing", role:"Netflix runs hundreds of experiments/year on discovery", rel:"Core methodology"},
      {name:"Content merchandising", role:"Positioning, promoting, presenting games alongside film/series", rel:"Team mission"},
      {name:"Cloud gaming infrastructure", role:"Games streamed to TV — technical context for product decisions", rel:"Domain context"},
      {name:"Phone-as-controller", role:"Mobile phone as game controller for TV games", rel:"Novel interaction"},
      {name:"Data science partnership", role:"Building business cases, measuring impact, experiment design", rel:"Core workflow"},
      {name:"Consumer insights", role:"Understanding member behavior, needs, and engagement patterns", rel:"Core workflow"},
    ],
  }},
  { id:"fit", title:"Fit Analysis", icon:"△", type:"fit", data:{
    strengths:[
      "Consumer product discovery on TV platforms — you literally built the fuboTV Home page, the primary discovery surface for a streaming TV product. Netflix Games Discovery is the same problem: how do members find and engage with content on a TV interface?",
      "Cross-platform product shipping — fuboTV across Roku, SmartTV, Apple TV, mobile, web. Netflix Games spans TV, mobile, tablet, web. Same multi-platform challenge.",
      "Quest OS Navigator — the highest-traffic discovery surface on Quest. You own the roadmap, write PRDs, prototype features. The Navigator IS a content discovery product.",
      "0-to-1 product development — Netflix Games discovery is still being defined. Your founder experience (ProjectNightOwl, Hostr, NexusWealth) demonstrates you can build new product categories from scratch.",
      "A/B testing and data-driven product development — you set KPIs/OKRs at fuboTV and partnered with product on experimentation. Netflix's culture of experimentation is your natural operating mode.",
      "Live sports integration on TV — your fuboTV live sports stat integration across platforms maps directly to Netflix's live streaming events (NFL, FIFA) and their intersection with games.",
      "Cross-functional leadership — the posting emphasizes partnering with design, engineering, consumer insights, merchandising, and data science. This is your EM DNA applied to a PM role.",
      "Content-product intersection — you sit at 'Product × Tech × Games Studio' which mirrors your current role at Meta where you sit at Product × Engineering × Design for Quest OS.",
      "Fully remote — Boca Raton works. PST hours and occasional CA travel are manageable.",
    ],
    adjacent:[
      "Your product work has been on streaming/entertainment platforms, not games specifically — but the DISCOVERY layer is the same problem regardless of content type. How do you surface the right content to the right user? That's what you've been doing.",
      "fuboTV live sports discovery → Netflix games discovery: both are 'how do you get members excited about a new content type on a platform they already use for something else?'",
      "Quest OS app library and navigation → Netflix games catalog: both are content discovery UIs for a growing catalog of diverse content types.",
    ],
    gaps:[
      {gap:"No games streaming product experience", critical:"HIGH", note:"The posting requires 'experience working on games streaming products at scale, and a great understanding of the games lifecycle.' You haven't worked on a games product. This is the biggest gap. However, you can argue: (1) discovery UX on TV platforms transfers directly, (2) you're a gamer yourself and understand the user, (3) Netflix wants someone who can shape a new category, which is founder territory.", time:"Narrative reframing + deep games industry research, 2-3 weeks"},
      {gap:"No formal PM title", critical:"MEDIUM", note:"The posting asks for 7+ years of 'developing consumer products.' You've been an EM who writes PRDs, owns roadmaps, and drives product decisions. The gap is title, not skill. Frame as 'product-minded engineering leader' — which is exactly what you are.", time:"Resume framing, already addressed"},
      {gap:"Games industry domain knowledge", critical:"MEDIUM", note:"Understanding games lifecycle, player engagement patterns, games-specific metrics (DAU, retention curves, session length, level completion). You'll need to speak fluently about how games differ from video content in discovery and engagement.", time:"2-3 weeks of deep study"},
      {gap:"Netflix Culture Memo", critical:"MEDIUM", note:"Same as all Netflix roles — the behavioral interview is make-or-break. Read it thoroughly.", time:"3-4 days"},
      {gap:"PST hours", critical:"LOW", note:"You're in Boca Raton (EST). Working PST hours means your core working day starts at noon EST. Netflix is explicit about this requirement since cross-functional partners are West Coast.", time:"Lifestyle adjustment"},
    ],
  }},
  { id:"knowledge", title:"Knowledge Map", icon:"▽", type:"knowledge", data:[
    {name:"Netflix Games Landscape", topics:["Current catalog: 93+ games across mobile (download) and cloud (streaming to TV)","Cloud-first strategy: why Netflix is pivoting from mobile-first to TV/cloud","Party games success: Boggle, Pictionary, LEGO Party — why shared play works","Phone-as-controller: using mobile as gamepad for TV games","IP-driven games: Stranger Things, Queen's Gambit Chess, Narcos — content synergy","Games lifecycle: how games are acquired, launched, promoted, and sunset on Netflix","Warner Bros. Discovery potential: Mortal Kombat, DC titles, studio capabilities","$140B market: how Netflix positions games as engagement, not revenue"], ai:"Play every Netflix game you can. Study the discovery UX on mobile and TV. Map every touchpoint where a member could discover a game. Ask Claude to analyze the gaps and propose 3 product concepts that would increase games discovery by 2x."},
    {name:"Games Discovery & Merchandising", topics:["Content merchandising: how Netflix positions and promotes content in the UI","Discovery surfaces: home row, dedicated tab, search, profile-specific recommendations","Cross-content discovery: how games appear alongside film/series recommendations","Personalization: how Netflix's recommendation engine could apply to games","Engagement metrics for games: DAU, session length, retention curves, return rate","Browse vs search vs recommendation: which discovery paths work for games","The 'awareness gap': most Netflix members don't know games exist — how to solve it","Kids profiles: games discovery for younger audiences with parental gating"], ai:"Ask Claude to design 3 different games discovery experiences for Netflix TV. Consider: a games-specific browse surface, inline game recommendations in video rows, post-credits game suggestions tied to IP (watched Stranger Things? Play the game). Compare tradeoffs."},
    {name:"Cloud Gaming Product Landscape", topics:["Cloud gaming fundamentals: streaming games from servers to devices","Competitor landscape: Xbox Cloud Gaming, PlayStation Now, NVIDIA GeForce NOW, Amazon Luna","Latency and quality tradeoffs in cloud gaming","TV-specific UX challenges: controller pairing, input lag, quality adaptation","Netflix's unique angle: games as part of subscription, not standalone","How cloud gaming on TV differs from mobile download games in discovery UX","Family/party games: why shared TV play is Netflix's early wedge"], ai:"Study how Xbox Cloud Gaming and Amazon Luna handle game discovery on TV. Compare their approaches. Ask Claude: 'What makes Netflix's position unique in cloud gaming? How should that uniqueness shape the discovery experience?'"},
    {name:"Product Management at Netflix", topics:["Strategy memos: Netflix PMs write long-form strategy documents, not slide decks","A/B testing culture: every feature ships as an experiment — design, measure, iterate","Data science partnership: PMs co-create business cases and experiment designs with DS","Consumer insights: qualitative research partnership for understanding member needs","Cross-functional influence: PMs at Netflix don't have direct authority — they influence","The 'connective tissue' role: this PM sits between Product, Tech, and Games Studio","Netflix product org structure: Product Merchandising → NCE team within it"], ai:"Ask Claude to help you draft a strategy memo for 'How Netflix Should Approach Games Discovery in 2027.' Practice the Netflix memo format: context, thesis, key questions, proposed approach, success metrics. This is your interview artifact."},
    {name:"Netflix Culture & Interview Prep", topics:["Culture Memo: Freedom & Responsibility, Dream Team, Keeper Test","PM interview format: strategy presentation, product sense, behavioral/cultural fit","Product sense: 'How would you improve games discovery on Netflix?'","Strategy: 'What should Netflix's games strategy be in 3 years?'","Behavioral: ownership, candor, ambiguity, feedback — same Netflix values as SWE roles","'Why Netflix Games?' — need a genuine, thoughtful answer","Compensation negotiation: $440K-$725K range is wide — need to articulate value"], ai:"Read the Culture Memo end-to-end. Ask Claude to run a mock PM interview with product sense questions about Netflix Games. Practice: 'You have 30 minutes to present your vision for games discovery to the VP of Product Merchandising. What do you say?'"},
  ]},
  { id:"plan", title:"30-Day Sprint", icon:"⬡", type:"plan", data:[
    {week:"Week 1: Games Immersion + Netflix Deep Dive", days:[
      {day:"Days 1-3", focus:"Play Netflix Games + Study Discovery UX", tasks:["Download Netflix mobile app and play 10+ games across different genres","Study the current games discovery flow: how many taps to find and launch a game?","If you have a compatible TV, try Netflix cloud games (Boggle, Pictionary)","Document every discovery touchpoint: home rows, games tab, search, recommendations","Screenshot and annotate: what works, what's broken, what's missing","Compare: how does Apple Arcade, Xbox Game Pass, and Steam handle discovery?"], hrs:"4-5 hrs/day"},
      {day:"Days 4-5", focus:"Netflix Games Strategy Research", tasks:["Read Netflix Q4 2025 earnings call transcript — games section thoroughly","Study Alain Tascan (Netflix Games president) interviews and talks","Research Netflix's game studios: acquired studios, in-house development","Understand the games lifecycle at Netflix: acquisition → launch → promotion → sunset","Map the competitive landscape: Apple Arcade, Google Play Pass, Xbox Game Pass","Study the Warner Bros. Discovery acquisition implications for games"], hrs:"3-4 hrs/day"},
      {day:"Days 6-7", focus:"Games Industry Fundamentals", tasks:["Study games-specific metrics: DAU, MAU, D1/D7/D30 retention, session length, ARPU","Understand the games lifecycle: soft launch → global launch → live ops → sunset","Study how games discovery works in app stores (iOS/Google Play) vs subscription services","Research: what makes game recommendations different from video recommendations?","Key question: how do you recommend a 40-hour RPG differently from a 5-minute puzzle?"], hrs:"3-4 hrs/day"},
    ]},
    {week:"Week 2: Product Strategy + Netflix Culture", days:[
      {day:"Days 8-10", focus:"Draft Your Games Discovery Strategy", tasks:["Write a strategy memo: 'The Future of Games Discovery on Netflix'","Structure: problem statement, current state, opportunity, proposed approach, success metrics","Include: 3 product concepts for improving games discovery across platforms","Address: how games discovery fits alongside film, series, live, podcasts on one platform","Get specific: what A/B tests would you run first? What metrics define success?","This becomes your interview artifact and shows you can do the job before you have it"], hrs:"4-5 hrs/day"},
      {day:"Days 11-12", focus:"Netflix Culture Memo + Behavioral Prep", tasks:["Read the Netflix Culture Memo thoroughly — actually internalize it","Prepare 10 STAR stories mapped to Netflix values","Focus on: building alignment while pushing through ambiguity, candor, ownership","Practice the 'Dream Team' behavioral round with Claude as interviewer","Prepare: 'Why Netflix Games? Why you? Why now?'"], hrs:"3-4 hrs/day"},
      {day:"Days 13-14", focus:"Cross-functional Storytelling", tasks:["Practice translating games goals into product strategy (the core of this role)","Draft a 1-page business case: 'Why investing in games discovery drives retention'","Study Netflix's data science partnership model — how PMs work with DS","Prepare to discuss: 'How would you measure the impact of a new games discovery feature?'"], hrs:"3-4 hrs/day"},
    ]},
    {week:"Week 3: Mock Interviews + Portfolio", days:[
      {day:"Days 15-17", focus:"Product Sense Practice", tasks:["Mock interview: 'How would you improve games discovery on Netflix TV?'","Mock interview: 'Netflix is launching a FIFA game on TV. Design the discovery experience.'","Mock interview: 'How do you balance games discovery vs film/series on the home screen?'","Mock interview: 'A game has great quality but low engagement. What do you do?'","Practice presenting your strategy memo in 15 minutes — clear, concise, compelling"], hrs:"3-4 hrs/day"},
      {day:"Days 18-19", focus:"Strategy Presentation Prep", tasks:["Netflix PM interviews often include presenting a strategy — polish yours","Create a visual artifact (deck or interactive brief) showing your games discovery vision","Include: user journey maps, wireframes (rough is fine), metric frameworks","Practice presenting to Claude as a VP of Product — get feedback, iterate"], hrs:"3-4 hrs/day"},
      {day:"Days 20-21", focus:"Full Mock Interview Loop", tasks:["Mock 1: Product sense (45 min)","Mock 2: Strategy presentation (30 min presentation + 15 min Q&A)","Mock 3: Behavioral / Dream Team round (45 min)","Identify weak areas and drill them"], hrs:"4-5 hrs/day"},
    ]},
    {week:"Week 4: Apply + Final Prep", days:[
      {day:"Days 22-25", focus:"Application Materials", tasks:["Tailor resume: lead with product discovery experience, TV platforms, consumer scale","Frame: fuboTV Home page = content discovery on TV. Quest OS Navigator = content discovery in spatial computing. Netflix Games = content discovery for games.","Include your strategy memo as a writing sample (if Netflix accepts supplementary materials)","Write a concise cover note connecting your background to this specific role"], hrs:"3-4 hrs/day"},
      {day:"Days 26-28", focus:"Final Prep", tasks:["Review games discovery strategy one more time — stress test your assumptions","Final mock interview: full loop simulation","Read the Culture Memo one more time","Prepare 5 thoughtful questions about the NCE team and games strategy"], hrs:"3-4 hrs/day"},
      {day:"Days 29-30", focus:"Submit + Network", tasks:["Submit application to Netflix PM, Games Discovery","Reach out to Netflix Games PMs and NCE team members on LinkedIn","Post about your games discovery analysis on Twitter (shows thought leadership)","Continue other applications in parallel"], hrs:"2-3 hrs/day"},
    ]},
  ]},
  { id:"tactics", title:"AI Tactics", icon:"□", type:"tactics", data:[
    {name:"Claude as Games Discovery Strategist", desc:"Draft and refine your games discovery strategy memo.", ex:"I'm preparing for a PM role at Netflix focused on games discovery. Help me draft a strategy memo: 'The Future of Games Discovery on Netflix.' Netflix has 93+ games, is pivoting to cloud-first gaming on TV, and the main challenge is that most members don't know games exist. Structure it like a Netflix strategy memo: context, problem, opportunity, proposed approach (3 product concepts), A/B test plan, success metrics."},
    {name:"Claude as Netflix PM Interviewer", desc:"Practice product sense questions specific to games discovery.", ex:"You're a Netflix VP of Product Merchandising interviewing me for the Games Discovery PM role. Ask me: 'Netflix's games have low awareness among members. Only 10% of eligible members have tried TV games. Present your plan to 5x that number in 12 months.' Push back on my ideas, ask follow-ups, and evaluate me on strategic thinking, metric design, and cross-functional awareness."},
    {name:"Claude as Competitive Analyst", desc:"Deep research on how competitors handle game discovery.", ex:"Compare how these platforms handle game discovery: Apple Arcade, Xbox Game Pass, PlayStation Plus, Steam, and Netflix Games. For each: how do users browse games? How are games recommended? What personalization exists? What's the 'time to first play'? Then tell me: what should Netflix steal, what should they avoid, and what's unique about Netflix's position?"},
    {name:"Claude as Games Metrics Tutor", desc:"Build fluency in games-specific product metrics.", ex:"Teach me games product metrics as if I'm a PM who's deep in streaming video but new to games. Cover: DAU/MAU ratio, D1/D7/D30 retention, session length, conversion-to-play, discovery-to-install funnel, engagement per session, lifetime play hours. How do these differ from video streaming metrics like completion rate, view hours, and retention? What metrics should a games discovery PM at Netflix obsess over?"},
  ]},
  { id:"res", title:"Resources", icon:"◈", type:"res", data:[
    {cat:"Must Do First", items:["Play 10+ Netflix games on mobile and TV","Netflix Q4 2025 earnings call transcript — games section","Netflix Culture Memo (jobs.netflix.com/culture)","Alain Tascan (Netflix Games president) interviews"]},
    {cat:"Games Industry", items:["Game Discoverability Report 2025 (industry reports on how players find games)","Apple Arcade, Xbox Game Pass, PlayStation Plus — study their discovery UX","GameDiscoverCo newsletter (industry insights on game discovery)","GDC talks on game discovery and merchandising"]},
    {cat:"Netflix Product", items:["Netflix Tech Blog — recommendation engine and personalization posts","Netflix research papers on content recommendation","Netflix A/B testing methodology (public talks and blog posts)","Study the Netflix UI on every platform: TV, iOS, Android, web"]},
    {cat:"Interview Prep", items:["Prepfully Netflix PM guide","Exponent Netflix PM interview guide","Practice: draft 3 strategy memos on Netflix product topics","Lewis C. Lin's 'Decode and Conquer' for PM interview frameworks"]},
  ]},
];

const Badge = ({color,children}) => {
  const c = {green:"bg-emerald-500/15 text-emerald-300 border-emerald-500/30",amber:"bg-amber-500/15 text-amber-300 border-amber-500/30",red:"bg-red-500/15 text-red-300 border-red-500/30",blue:"bg-blue-500/15 text-blue-300 border-blue-500/30",gray:"bg-gray-500/15 text-gray-300 border-gray-500/30"};
  return <span className={`text-xs px-2 py-0.5 rounded-full border font-mono ${c[color]}`}>{children}</span>;
};
const Opp = ({d}) => (<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[["ROLE",d.role],["COMP",d.comp],["TEAM",d.team],["LOCATION",d.loc]].map(([l,v])=><div key={l} className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">{l}</div><div className="text-white text-sm">{v}</div></div>)}</div><div className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">FOCUS</div><div className="text-white text-sm">{d.focus}</div></div><div className="bg-emerald-900/20 border border-emerald-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">WHY NOW</div><div className="text-emerald-200 text-sm leading-relaxed">{d.whyNow}</div></div><div className="bg-amber-900/20 border border-amber-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">STATUS</div><div className="text-amber-200 text-sm">{d.status}</div></div><div className="bg-blue-900/20 border border-blue-500/30 rounded-lg p-4"><div className="text-xs tracking-widest text-blue-400 mb-1.5 font-mono">ASSESSMENT</div><div className="text-blue-200 text-sm">{d.verdict}</div></div></div>);
const Intel = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">NETFLIX GAMES — CURRENT STATE</div>{d.news.map((n,i)=><div key={i} className="bg-white/5 border border-white/10 rounded-lg p-3 mb-2"><div className="text-white text-sm font-medium mb-1">{n.e}</div><div className="text-gray-400 text-sm">{n.d}</div></div>)}</div><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">PRODUCT SURFACE</div>{d.stack.map((s,i)=><div key={i} className="flex items-center gap-3 py-1.5"><Badge color={s.rel.includes("Core")?"green":s.rel.includes("Novel")?"amber":"gray"}>{s.rel}</Badge><span className="text-white text-sm font-medium min-w-40">{s.name}</span><span className="text-gray-500 text-sm">{s.role}</span></div>)}</div></div>);
const FitView = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">STRENGTHS — DISCOVERY IS YOUR WHEELHOUSE</div>{d.strengths.map((s,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-emerald-400 mt-0.5 text-xs">✓</span><span className="text-gray-300 text-sm">{s}</span></div>)}</div><div><div className="text-xs tracking-widest text-blue-400 mb-3 font-mono">REFRAME — THE DISCOVERY LAYER TRANSFERS</div>{d.adjacent.map((a,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-blue-400 mt-0.5 text-xs">↗</span><span className="text-gray-300 text-sm">{a}</span></div>)}</div><div><div className="text-xs tracking-widest text-red-400 mb-3 font-mono">GAPS — THE GAMES EXPERIENCE QUESTION</div>{d.gaps.map((g,i)=><div key={i} className="border border-white/10 rounded-lg p-3 mb-2"><div className="flex items-center gap-2 mb-1"><span className="text-white text-sm font-medium">{g.gap}</span><Badge color={g.critical==="HIGH"?"red":"amber"}>{g.critical}</Badge></div><p className="text-gray-400 text-sm">{g.note}</p><div className="text-xs text-gray-600 font-mono mt-1">Close in: {g.time}</div></div>)}</div></div>);
const KMap = ({d}) => {const [exp,setExp]=useState(null);return <div className="space-y-2">{d.map((k,i)=><div key={i} className="border border-white/10 rounded-lg overflow-hidden"><button onClick={()=>setExp(exp===i?null:i)} className="w-full text-left p-4 flex items-center justify-between hover:bg-white/5 transition-colors"><span className="text-white font-medium text-sm">{k.name}</span><span className="text-gray-500">{exp===i?"−":"+"}</span></button>{exp===i&&<div className="px-4 pb-4 border-t border-white/5"><div className="mt-3 space-y-1.5">{k.topics.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-amber-400 mt-1 text-xs">›</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div><div className="mt-3 bg-blue-900/20 border border-blue-500/20 rounded-lg p-3"><div className="text-xs tracking-widest text-blue-400 mb-1 font-mono">AI ACCELERATION</div><p className="text-blue-200 text-sm">{k.ai}</p></div></div>}</div>)}</div>};
const Plan = ({d}) => {const [aw,setAw]=useState(0);const w=d[aw];return <div><div className="flex gap-2 mb-4 overflow-x-auto">{d.map((_,i)=><button key={i} onClick={()=>setAw(i)} className={`px-3 py-1.5 rounded-lg text-xs font-mono whitespace-nowrap transition-all ${aw===i?"bg-amber-500/20 text-amber-300 border border-amber-500/40":"bg-white/5 text-gray-400 border border-white/10"}`}>Wk {i+1}</button>)}</div><h4 className="text-white font-medium mb-4">{w.week}</h4><div className="space-y-4">{w.days.map((d,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="flex items-center justify-between mb-3"><div><span className="text-amber-400 font-mono text-xs">{d.day}</span><span className="text-gray-500 mx-2">·</span><span className="text-white text-sm font-medium">{d.focus}</span></div><span className="text-gray-600 text-xs font-mono">{d.hrs}</span></div><div className="space-y-1.5">{d.tasks.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-gray-600 mt-0.5 text-xs font-mono">{String(j+1).padStart(2,"0")}</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div></div>)}</div></div>};
const Tactics = ({d}) => <div className="space-y-4">{d.map((t,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="text-white font-medium text-sm mb-1">{t.name}</div><p className="text-gray-400 text-sm mb-3">{t.desc}</p><div className="bg-gray-900 rounded-lg p-3 border border-white/5"><div className="text-xs text-gray-600 font-mono mb-1">PROMPT</div><p className="text-amber-300 text-sm italic">"{t.ex}"</p></div></div>)}</div>;
const Res = ({d}) => <div className="space-y-6">{d.map((c,i)=><div key={i}><div className="text-xs tracking-widest text-amber-400 mb-2 font-mono">{c.cat.toUpperCase()}</div>{c.items.map((item,j)=><div key={j} className="flex items-start gap-2 mb-1"><span className="text-gray-600 mt-0.5 text-xs">›</span><span className="text-gray-300 text-sm">{item}</span></div>)}</div>)}</div>;
const R = {opp:Opp,intel:Intel,fit:FitView,knowledge:KMap,plan:Plan,tactics:Tactics,res:Res};

export default function Brief() {
  const [a,setA] = useState("opp");
  const s = S.find(x=>x.id===a);
  const V = R[s.type];
  return (
    <div className="min-h-screen text-white" style={{background:"linear-gradient(160deg,#090909 0%,#0e0e0e 50%,#0a0a0a 100%)",fontFamily:"'IBM Plex Sans',sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap');.font-mono{font-family:'IBM Plex Mono',monospace}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.1);border-radius:2px}`}</style>
      <div className="border-b border-white/10 px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-3"><div className="w-2 h-2 bg-amber-400 rounded-full animate-pulse"/><span className="text-xs font-mono text-gray-500 tracking-widest">JOB PREP INTELLIGENCE BRIEF — COMPELLING BUT STRETCH</span></div><h1 className="text-2xl md:text-3xl font-light text-white mb-2" style={{letterSpacing:"-0.02em"}}>Netflix · PM, Games Discovery</h1><p className="text-gray-500 text-sm">$440K-$725K · Remote · Shape how 300M members discover games · 30-day sprint</p></div></div>
      <div className="border-b border-white/10 px-6 py-3 sticky top-0 z-10" style={{background:"rgba(9,9,9,0.95)",backdropFilter:"blur(12px)"}}><div className="max-w-4xl mx-auto flex gap-1 overflow-x-auto">{S.map(x=><button key={x.id} onClick={()=>setA(x.id)} className={`px-3 py-1.5 rounded-md text-xs font-mono whitespace-nowrap transition-all ${a===x.id?"bg-white/10 text-white":"text-gray-600 hover:text-gray-400"}`}><span className="mr-1.5">{x.icon}</span>{x.title}</button>)}</div></div>
      <div className="px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-6"><span className="text-amber-400 text-lg">{s.icon}</span><h2 className="text-xl font-light text-white">{s.title}</h2></div><V d={s.data}/></div></div>
      <div className="border-t border-white/5 px-6 py-4"><div className="max-w-4xl mx-auto text-center"><p className="text-gray-700 text-xs font-mono">~100 hrs over 30 days · games industry immersion + strategy memo + culture prep</p></div></div>
    </div>
  );
}
