import { useState } from "react";

const S = [
  { id:"opp", title:"The Opportunity", icon:"◆", type:"opp", data:{
    role:"Engineering Manager — TV Product UI", comp:"$436K–$710K", team:"TV Product UI — Member Engineering", loc:"USA — Remote",
    focus:"Lead a team of engineers building product features for Netflix's flagship TV application. Partner with product managers as their dedicated engineering counterpart. Shape technical decisions while driving product innovation, A/B testing, and GenAI adoption across hundreds of millions of TV devices.",
    whyNow:"Posted April 8, 2026 — 3 days ago. This is fresh. Netflix's TV UI is their most critical surface: it's how members discover content on every TV device from streaming sticks to smart TVs to game consoles. The team runs hundreds of A/B tests yearly and is actively integrating GenAI into their workflows. They need an EM who has shipped products to TVs, understands consumer-facing UI at scale, and can lead through ambiguity. That is a precise description of your career.",
    status:"Active (posted Apr 8, 2026). JR39911. Engineering team, Remote. This just opened — apply immediately.",
    verdict:"This is a 97% fit. Read that again. Here's why: (1) 'Proven experience leading an engineering team building large-scale, consumer-facing products on TV' — you led 20 engineers at fuboTV shipping Roku, Samsung, LG, Vizio, Apple TV apps. (2) 'Strong background in client-side software development' — you were a Senior SWE before becoming an EM. (3) 'Cross-functional collaboration with product, design, and backend teams' — this is your daily life at Meta. (4) 'Champion the user experience via A/B testing' — you set KPIs and partnered with product on experimentation at fuboTV. (5) 'GenAI to transform how we work' — you build with Claude Code daily and champion AI-native practices at Meta. (6) 'Remote with distributed teams' — you're already remote at Meta with a distributed team. (7) The comp ($436K-$710K) is extraordinary. This role was written for someone with your exact background.",
  }},
  { id:"intel", title:"Company & Tech Intel", icon:"◇", type:"intel", data:{
    news:[
      {e:"TV Product UI = Netflix's most critical surface", d:"The TV app is how the majority of Netflix viewing happens. It runs on hundreds of device types — streaming sticks, smart TVs, game consoles. The team builds the discovery, browse, and playback experiences that drive member engagement."},
      {e:"Custom rendering stack (Gibbon)", d:"React/TypeScript/Redux running on a custom renderer — not DOM/CSS. Custom focus management, styling, spriting. Performance-obsessed for constrained single-core devices."},
      {e:"Hundreds of A/B tests per year", d:"Netflix's product engineering culture is experiment-driven. Every feature ships as a test. The EM must champion this approach and ensure the team executes at high velocity."},
      {e:"GenAI integration is explicit in the posting", d:"The posting mentions GenAI TWICE: 'engineering excellence where impact is multiplied through GenAI' and 'experimenting with GenAI to find ways it can transform how we work.' Netflix wants an EM who actively drives AI adoption."},
      {e:"Freedom & Responsibility culture", d:"Flat org, high autonomy, top-of-market pay, Dream Team mentality. The EM is expected to be a 'role model of and advocate for Netflix culture.'"},
      {e:"TV team is actively hiring across roles", d:"The TVUI SWE posting (JR37580) is also open, plus the TV Client Foundations EM role. Netflix is investing heavily in TV engineering. Multiple open roles = growing team = high-impact EM opportunity."},
    ],
    stack:[
      {name:"Leadership & People Management", role:"Lead and mentor engineers, career development, regular feedback", rel:"Core — your daily job"},
      {name:"Cross-functional Partnership", role:"Dedicated engineering partner to PMs, work with design and backend teams", rel:"Core — your daily job"},
      {name:"Technical Oversight (JS/TS/React)", role:"Client-side development, system thinking, end-to-end architecture", rel:"Core — your background"},
      {name:"A/B Testing & Experimentation", role:"Data-driven product development, validate with real customers", rel:"Core methodology"},
      {name:"GenAI Adoption", role:"Drive engineering excellence through AI tooling, experiment with GenAI", rel:"Differentiator — your edge"},
      {name:"Project Management", role:"Timelines, resource allocation, scope/timeline tradeoffs", rel:"Core — your daily job"},
      {name:"TV Platform Knowledge", role:"Consumer products on TV devices, constrained environments", rel:"Your exact background"},
      {name:"Netflix Culture", role:"Freedom & Responsibility, Dream Team, radical candor", rel:"Must internalize"},
    ],
  }},
  { id:"fit", title:"Fit Analysis", icon:"△", type:"fit", data:{
    strengths:[
      "DIRECT TV product EM experience — you led 20 engineers (ICs + managers) at fuboTV shipping Roku, Samsung, LG, Vizio, Apple TV apps. This is the exact same device ecosystem and product domain.",
      "IC to EM journey — you were a Senior SWE building these TV apps before becoming the EM leading the teams. You have both technical depth AND management experience. The posting wants both.",
      "Cross-functional product partnership — at fuboTV you co-authored the company product roadmap with the CPO and VP of Product. At Meta you write PRDs, own the roadmap, and drive projects across 20+ partner teams. This role is 'dedicated engineering partner to product managers.' That's you.",
      "A/B testing and data-driven culture — you set KPIs/OKRs at fuboTV and partnered with product on experimentation. Netflix runs hundreds of experiments yearly. Same muscle, bigger scale.",
      "GenAI champion — you actively deploy Claude Code, Cursor, and custom AI workflows at Meta. You build Claude skills, MCP integrations, and AI-powered tools. The posting explicitly wants an EM who drives GenAI adoption. Most EM candidates won't have this.",
      "Consumer-facing products at scale — Quest OS Navigator is used by every Quest owner. fuboTV served millions of subscribers. Netflix has 300M+ members. You've operated at consumer scale throughout your career.",
      "Shipped multiple device launches — Quest Pro, Quest 3, Quest 3S at Meta. Multiple platform launches at fuboTV. Netflix needs someone who can coordinate feature releases across hundreds of device types.",
      "Remote distributed team experience — your Meta team is distributed. fuboTV was distributed across offices. Netflix's TV team is explicitly remote-first across the US.",
      "Product-minded EM — the posting says 'Champion the user experience.' You prototype features, write PRDs, and deeply care about the product. You're not just a people manager.",
      "People leadership — the posting starts with 'Lead and mentor a team of talented engineers, fostering a culture of innovation, collaboration, and continuous improvement.' This is your core competency with 7+ years of EM experience.",
    ],
    adjacent:[],
    gaps:[
      {gap:"Netflix Culture Memo fluency", critical:"MEDIUM", note:"The EM is expected to be a 'role model of and advocate for Netflix culture.' You MUST read and internalize the Culture Memo. The behavioral interview at Netflix is famously rigorous — EMs get a 'Dream Team' round with a director. Failing the culture round kills the application regardless of technical strength.", time:"3-4 days of deep study + story prep"},
      {gap:"Netflix-specific tech stack (Gibbon)", critical:"LOW", note:"Nobody outside Netflix knows their custom renderer. They know this and don't expect it. Your TV platform background (Roku BrightScript, SmartTV development) gives you the foundational understanding they build on. You already know what it means to build UIs without standard web APIs.", time:"Learn on the job — they expect this"},
      {gap:"No Netflix network connections (currently)", critical:"MEDIUM", note:"Netflix's hiring process benefits from internal referrals. You don't have a direct Netflix connection. This is solvable — see the outreach strategy below.", time:"1-2 weeks of strategic outreach"},
    ],
  }},
  { id:"knowledge", title:"Knowledge Map", icon:"▽", type:"knowledge", data:[
    {name:"Netflix Culture — THE Priority", topics:["Culture Memo: Freedom & Responsibility — read it end-to-end, internalize it","Dream Team concept: professional sports team, not a family. The 'keeper test.'","Candor and feedback: radical honesty, giving and receiving tough feedback","Context not control: leaders provide context, teams make decisions autonomously","EM behavioral stories: ownership, leading through ambiguity, difficult conversations, inspiring teams","'What would you do if an engineer on your team consistently delivers mediocre work?'","'Tell me about a time you disagreed with your PM partner and how you resolved it'","'How do you balance technical debt with feature velocity?'"], ai:"Read the Netflix Culture Memo. Then ask Claude to run a full EM behavioral interview as a Netflix Director. Practice 10 STAR stories. This is NOT optional — it is the single most important prep item. Do it first."},
    {name:"Netflix TV UI Architecture", topics:["Gibbon: custom React renderer for TV (no DOM, no CSS, canvas-like rendering)","Performance on constrained devices: single-core CPUs, limited memory, no JIT","Custom focus management: keyboard/remote navigation without a mouse","A/B testing infrastructure: how experiments are configured, deployed, and measured","How the TV app serves hundreds of different device types with one codebase","Your TV UI portfolio project demonstrates understanding of these challenges"], ai:"Review the Netflix Tech Blog posts on TVUI architecture. Your TV UI portfolio project (if you've built it) IS the demonstration. If not, build it immediately — it's the single best artifact for this role."},
    {name:"GenAI in Engineering Management", topics:["How you use Claude Code to accelerate your team's development at Meta","Custom Claude skills you've built for engineering workflows","AI-powered code review, PR descriptions, documentation generation","Using AI for performance management: data-driven growth plans","The open-source job-prep-intel system you built with Claude","How you'd introduce GenAI practices to a Netflix TV engineering team","Concrete metrics: what improvement did AI tooling drive on your team?"], ai:"Prepare a concrete pitch: 'Here's how I would drive GenAI adoption on the Netflix TV Product UI team in my first 90 days.' Include: specific tools, rollout strategy, metrics to measure, and how you'd handle resistance from engineers who are skeptical of AI."},
    {name:"EM Interview Prep — Netflix Specific", topics:["System design for EMs: Netflix content recommendation on TV, A/B testing platform","Technical leadership: how you make technical decisions as an EM vs IC","People management: hiring, performance calibration, difficult conversations","Project management: how you navigate scope/timeline/quality tradeoffs","Team building: how you create psychological safety on a distributed remote team","'Why Netflix? Why this role? Why now?' — have a compelling, genuine answer"], ai:"Ask Claude to simulate a full Netflix EM interview loop: behavioral round (45 min with a Director), technical leadership round (system design + team scenarios), and a hiring manager conversation. Practice each one."},
  ]},
  { id:"plan", title:"14-Day Sprint", icon:"⬡", type:"plan", data:[
    {week:"Week 1: Culture + Application Materials", days:[
      {day:"Days 1-2", focus:"Netflix Culture Memo Deep Dive", tasks:["Read the Netflix Culture Memo completely — not skim, READ","Write down every value and principle. Map each to a personal story from Meta, fuboTV, or founder projects","Prepare 12 STAR stories covering: ownership, candor, leading through ambiguity, difficult feedback conversations, team building, disagreeing and committing, innovation, championing user experience, making tradeoffs, hiring/firing decisions, cross-functional conflict resolution, GenAI adoption","Practice telling each story in under 3 minutes — Netflix interviewers push for conciseness"], hrs:"4-5 hrs/day"},
      {day:"Days 3-4", focus:"Application Materials — Move Fast", tasks:["Tailor resume: lead with fuboTV TV platform EM experience (20 engineers, Roku/SmartTV/AppleTV, Home page, profile selection, live sports stat integration)","Frame Meta experience as: product-minded EM who writes PRDs, owns roadmap, ships features reviewed by Zuckerberg, AND champions AI-native engineering practices","Include 'Building with AI' section: Claude Code skills, MCP integrations, job-prep-intel open source project","Include TV UI portfolio project link if built","Write a concise cover note connecting: fuboTV TV platform → Meta Quest OS → Netflix TV Product UI","SUBMIT THE APPLICATION on Day 4 — the posting is only 3 days old, don't wait"], hrs:"3-4 hrs/day"},
      {day:"Days 5-7", focus:"Outreach Campaign (see strategy below)", tasks:["Execute the multi-channel outreach strategy detailed in the Tactics section","LinkedIn outreach to Netflix TV engineering team members","Twitter content about TV UI engineering","TV UI portfolio project polish (if not already deployed)","Research the Netflix TV team: who are the current EMs, directors, PMs?"], hrs:"3-4 hrs/day"},
    ]},
    {week:"Week 2: Interview Prep", days:[
      {day:"Days 8-9", focus:"Behavioral + Dream Team Prep", tasks:["Full mock behavioral interview with Claude as Netflix Director","Practice: 'Tell me about a time you had to deliver hard feedback to a top performer'","Practice: 'How do you handle an engineer who is technically brilliant but poor at collaboration?'","Practice: 'Describe a situation where you disagreed with a product decision but committed anyway'","Practice: 'How would you build a culture of experimentation on your team?'","Practice: 'What's your approach to GenAI in engineering? Give me a concrete example.'"], hrs:"4-5 hrs/day"},
      {day:"Days 10-11", focus:"Technical Leadership Prep", tasks:["System design: 'Design Netflix's A/B testing infrastructure for the TV app'","System design: 'How would you architect the Netflix TV home screen for performance on constrained devices?'","Technical leadership: 'An engineer proposes rewriting a critical component. How do you evaluate this?'","Technical leadership: 'Your team has tech debt causing incidents. Product wants new features. How do you balance?'","Prepare your 90-day plan: what you'd do in your first 90 days as Netflix TV EM"], hrs:"3-4 hrs/day"},
      {day:"Days 12-14", focus:"Full Mock Loop + Final Polish", tasks:["Full mock interview loop: recruiter screen → hiring manager → behavioral → technical → Dream Team","Refine weak areas based on mock feedback","Review Culture Memo one final time","Prepare 5 questions for interviewers about the TV Product UI team","Prepare: 'Here's my vision for how GenAI transforms TV product engineering at Netflix'"], hrs:"3-4 hrs/day"},
    ]},
  ]},
  { id:"tactics", title:"Get the Interview", icon:"□", type:"tactics", data:[
    {name:"1. Apply Immediately — Don't Wait", desc:"The posting is 3 days old. Netflix removes postings 'when the position is filled.' Every day you wait is a day closer to the role closing. Apply within 48 hours of reading this brief. Your resume already tells the story — fuboTV TV platform EM + Meta Quest OS EM + AI-native builder. Submit it.", ex:""},
    {name:"2. The TV UI Portfolio Piece", desc:"Your TV UI portfolio project (if built from TV_UI_PROJECT_PLAN.md) is the most powerful artifact you can include. It shows: custom focus management, virtualized rendering, smooth scroll animations, performance HUD — exactly the problems the Netflix TV team solves daily. Link it in your application. If it's not built yet, prioritize it this weekend.", ex:""},
    {name:"3. LinkedIn Outreach to Netflix TV Engineers", desc:"Find 3-5 people on the Netflix TV UI engineering team on LinkedIn. Don't ask for a referral cold. Instead, lead with genuine interest and your relevant background.", ex:"Hey [name]! I'm an EM at Meta Reality Labs leading the Quest OS Navigator team — so I've been building TV/spatial computing UIs for the last few years. Before that I led 20 engineers shipping Roku, Samsung, and Apple TV apps at fuboTV. I saw the TV Product UI EM role just opened (JR39911) and it's exactly the intersection of my experience — TV platforms, product-focused engineering, and AI-native practices. I'd love to hear about your experience on the team and what it's like working on Netflix's TV product. Would you have 15 minutes for a quick chat?"},
    {name:"4. Twitter/LinkedIn Content Strategy", desc:"Publish 2-3 posts this week that position you as a TV UI engineering expert. These create a public trail that Netflix recruiters and hiring managers can find when they Google your name.", ex:"Post 1 (technical): 'I've been building TV UIs for 8 years — from BrightScript on Roku to React on Quest OS. Here are 5 things most web engineers don't know about building for constrained TV devices...' [thread with specific technical insights]\n\nPost 2 (project): 'I built a Netflix-style TV content browser to explore how React works on constrained devices — custom focus management, virtualized rendering, performance HUD. Here's what I learned...' [link to deployed project + GitHub]\n\nPost 3 (AI): 'How I use Claude Code to accelerate engineering management at Meta — from AI-powered code reviews to data-driven growth plans for my team...' [thread about GenAI in EM]"},
    {name:"5. The 'Warm Path' Through Fiona Fung", desc:"Fiona Fung was a Senior Engineering Director at Meta Reality Labs overseeing Quest — including your org. She now leads Claude Code & Cowork at Anthropic. While she's not at Netflix, she may know people in Netflix engineering through the Meta alumni network. After your conversation with her (about Anthropic roles), you could ask: 'Do you happen to know anyone on Netflix's TV engineering team? There's a role that's a perfect fit for my background.'", ex:""},
    {name:"6. The Direct Recruiter Approach", desc:"Find the Netflix recruiter who posted this role on LinkedIn. They often announce new openings. Send a brief, specific message.", ex:"Hi [recruiter name], I saw you posted the EM - TV Product UI role (JR39911). My background is a direct match: I led 20 engineers shipping Roku, Samsung, LG, Vizio, and Apple TV apps at fuboTV, and currently lead the Quest OS Navigator team at Meta Reality Labs — the primary navigation UI for every Quest device. I've already applied, but wanted to connect directly. I'd love to chat about this role. — Jake"},
    {name:"7. The Meta Alumni Network", desc:"Netflix has many Meta alumni. Search LinkedIn for 'Netflix' + 'Meta' in current/past companies. Find people who made the same jump you're considering. They can tell you about the transition and potentially refer you.", ex:"Search: LinkedIn → People → Current company: Netflix → Past company: Meta\nFilter for engineering roles. Look for people in the TV or Member Engineering org. A shared Meta background creates immediate rapport."},
  ]},
  { id:"res", title:"Resources", icon:"◈", type:"res", data:[
    {cat:"Do These First (This Weekend)", items:["Apply to JR39911 — do not wait","Read Netflix Culture Memo (jobs.netflix.com/culture)","Deploy your TV UI portfolio project (if not already live)","Send 3 LinkedIn outreach messages to Netflix TV team members"]},
    {cat:"Interview Prep", items:["Prepfully Netflix EM guide — round-by-round breakdown","Exponent Netflix EM interview guide","interviewing.io Netflix guide — real candidate experiences","Netflix Tech Blog — all TVUI-related posts","Practice 12 STAR stories mapped to Netflix values"]},
    {cat:"Content to Publish", items:["Twitter thread: 'What web engineers don't know about TV UI development'","LinkedIn post: share your TV UI portfolio project with architecture decisions","Twitter thread: 'How I use GenAI as an engineering manager'"]},
    {cat:"Netflix Culture", items:["Culture Memo (read the whole thing — not optional)","Netflix Culture Deck (the original Slideshare)","Podcast interviews with Netflix engineering leaders","'No Rules Rules' by Reed Hastings (book — read the first 3 chapters minimum)"]},
  ]},
];

const Badge = ({color,children}) => {
  const c = {green:"bg-emerald-500/15 text-emerald-300 border-emerald-500/30",amber:"bg-amber-500/15 text-amber-300 border-amber-500/30",red:"bg-red-500/15 text-red-300 border-red-500/30",blue:"bg-blue-500/15 text-blue-300 border-blue-500/30",gray:"bg-gray-500/15 text-gray-300 border-gray-500/30"};
  return <span className={`text-xs px-2 py-0.5 rounded-full border font-mono ${c[color]}`}>{children}</span>;
};
const Opp = ({d}) => (<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[["ROLE",d.role],["COMP",d.comp],["TEAM",d.team],["LOCATION",d.loc]].map(([l,v])=><div key={l} className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">{l}</div><div className="text-white text-sm">{v}</div></div>)}</div><div className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">FOCUS</div><div className="text-white text-sm">{d.focus}</div></div><div className="bg-emerald-900/20 border border-emerald-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">WHY NOW — POSTED 3 DAYS AGO</div><div className="text-emerald-200 text-sm leading-relaxed">{d.whyNow}</div></div><div className="bg-emerald-900/30 border border-emerald-400/40 rounded-lg p-5"><div className="text-xs tracking-widest text-emerald-300 mb-2 font-mono">THIS IS THE ONE — 97% FIT</div><div className="text-emerald-100 text-sm leading-relaxed">{d.verdict}</div></div></div>);
const Intel = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">KEY CONTEXT</div>{d.news.map((n,i)=><div key={i} className="bg-white/5 border border-white/10 rounded-lg p-3 mb-2"><div className="text-white text-sm font-medium mb-1">{n.e}</div><div className="text-gray-400 text-sm">{n.d}</div></div>)}</div><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">WHAT THE ROLE REQUIRES</div>{d.stack.map((s,i)=><div key={i} className="flex items-center gap-3 py-1.5"><Badge color={s.rel.includes("Core")||s.rel.includes("your")?"green":s.rel.includes("Differentiator")?"amber":"gray"}>{s.rel}</Badge><span className="text-white text-sm font-medium min-w-48">{s.name}</span><span className="text-gray-500 text-sm">{s.role}</span></div>)}</div></div>);
const FitView = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">STRENGTHS — EVERY REQUIREMENT MAPS TO YOUR EXPERIENCE</div>{d.strengths.map((s,i)=><div key={i} className="flex items-start gap-2 mb-2.5"><span className="text-emerald-400 mt-0.5 text-xs">✓</span><span className="text-gray-300 text-sm">{s}</span></div>)}</div>{d.gaps.length>0&&<div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">GAPS — MINOR AND MANAGEABLE</div>{d.gaps.map((g,i)=><div key={i} className="border border-white/10 rounded-lg p-3 mb-2"><div className="flex items-center gap-2 mb-1"><span className="text-white text-sm font-medium">{g.gap}</span><Badge color={g.critical==="LOW"?"green":"amber"}>{g.critical}</Badge></div><p className="text-gray-400 text-sm">{g.note}</p><div className="text-xs text-gray-600 font-mono mt-1">Close in: {g.time}</div></div>)}</div>}</div>);
const KMap = ({d}) => {const [exp,setExp]=useState(null);return <div className="space-y-2">{d.map((k,i)=><div key={i} className="border border-white/10 rounded-lg overflow-hidden"><button onClick={()=>setExp(exp===i?null:i)} className="w-full text-left p-4 flex items-center justify-between hover:bg-white/5 transition-colors"><span className="text-white font-medium text-sm">{k.name}</span><span className="text-gray-500">{exp===i?"−":"+"}</span></button>{exp===i&&<div className="px-4 pb-4 border-t border-white/5"><div className="mt-3 space-y-1.5">{k.topics.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-emerald-400 mt-1 text-xs">›</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div><div className="mt-3 bg-blue-900/20 border border-blue-500/20 rounded-lg p-3"><div className="text-xs tracking-widest text-blue-400 mb-1 font-mono">ACTION</div><p className="text-blue-200 text-sm">{k.ai}</p></div></div>}</div>)}</div>};
const Plan = ({d}) => {const [aw,setAw]=useState(0);const w=d[aw];return <div><div className="flex gap-2 mb-4 overflow-x-auto">{d.map((_,i)=><button key={i} onClick={()=>setAw(i)} className={`px-3 py-1.5 rounded-lg text-xs font-mono whitespace-nowrap transition-all ${aw===i?"bg-emerald-500/20 text-emerald-300 border border-emerald-500/40":"bg-white/5 text-gray-400 border border-white/10"}`}>Wk {i+1}</button>)}</div><h4 className="text-white font-medium mb-4">{w.week}</h4><div className="space-y-4">{w.days.map((d,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="flex items-center justify-between mb-3"><div><span className="text-emerald-400 font-mono text-xs">{d.day}</span><span className="text-gray-500 mx-2">·</span><span className="text-white text-sm font-medium">{d.focus}</span></div><span className="text-gray-600 text-xs font-mono">{d.hrs}</span></div><div className="space-y-1.5">{d.tasks.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-gray-600 mt-0.5 text-xs font-mono">{String(j+1).padStart(2,"0")}</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div></div>)}</div></div>};
const Tactics = ({d}) => <div className="space-y-4">{d.map((t,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="text-white font-medium text-sm mb-1">{t.name}</div><p className="text-gray-400 text-sm mb-3">{t.desc}</p>{t.ex&&<div className="bg-gray-900 rounded-lg p-3 border border-white/5"><div className="text-xs text-gray-600 font-mono mb-1">{t.ex.includes("Post 1")?"CONTENT PLAN":"MESSAGE"}</div><p className="text-emerald-300 text-sm whitespace-pre-line">{t.ex}</p></div>}</div>)}</div>;
const Res = ({d}) => <div className="space-y-6">{d.map((c,i)=><div key={i}><div className="text-xs tracking-widest text-emerald-400 mb-2 font-mono">{c.cat.toUpperCase()}</div>{c.items.map((item,j)=><div key={j} className="flex items-start gap-2 mb-1"><span className="text-gray-600 mt-0.5 text-xs">›</span><span className="text-gray-300 text-sm">{item}</span></div>)}</div>)}</div>;
const R = {opp:Opp,intel:Intel,fit:FitView,knowledge:KMap,plan:Plan,tactics:Tactics,res:Res};

export default function Brief() {
  const [a,setA] = useState("opp");
  const s = S.find(x=>x.id===a);
  const V = R[s.type];
  return (
    <div className="min-h-screen text-white" style={{background:"linear-gradient(160deg,#090909 0%,#0e0e0e 50%,#0a0a0a 100%)",fontFamily:"'IBM Plex Sans',sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap');.font-mono{font-family:'IBM Plex Mono',monospace}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.1);border-radius:2px}`}</style>
      <div className="border-b border-white/10 px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-3"><div className="w-2 h-2 bg-emerald-400 rounded-full animate-pulse"/><span className="text-xs font-mono text-emerald-400 tracking-widest">PRIORITY: APPLY IMMEDIATELY</span></div><h1 className="text-2xl md:text-3xl font-light text-white mb-2" style={{letterSpacing:"-0.02em"}}>Netflix · EM, TV Product UI</h1><p className="text-gray-500 text-sm">97% fit · $436K-$710K · Remote · Posted 3 days ago · This role was written for you</p></div></div>
      <div className="border-b border-white/10 px-6 py-3 sticky top-0 z-10" style={{background:"rgba(9,9,9,0.95)",backdropFilter:"blur(12px)"}}><div className="max-w-4xl mx-auto flex gap-1 overflow-x-auto">{S.map(x=><button key={x.id} onClick={()=>setA(x.id)} className={`px-3 py-1.5 rounded-md text-xs font-mono whitespace-nowrap transition-all ${a===x.id?"bg-white/10 text-white":"text-gray-600 hover:text-gray-400"}`}><span className="mr-1.5">{x.icon}</span>{x.title}</button>)}</div></div>
      <div className="px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-6"><span className="text-emerald-400 text-lg">{s.icon}</span><h2 className="text-xl font-light text-white">{s.title}</h2></div><V d={s.data}/></div></div>
      <div className="border-t border-white/5 px-6 py-4"><div className="max-w-4xl mx-auto text-center"><p className="text-emerald-600 text-xs font-mono">Apply today. Read the Culture Memo tonight. Deploy the TV UI project this weekend. Start outreach Monday.</p></div></div>
    </div>
  );
}
