import { useState } from "react";

export const tasks = [
  { title: "TV UI Portfolio Project", type: "project", roles: ["netflix-tvui-engineer"], status: "not-started", desc: "React + TypeScript content browser with keyboard nav, focus management, no mouse", priority: "high" },
  { title: "A/B Testing Framework Demo", type: "project", roles: ["netflix-tvui-engineer"], status: "not-started", desc: "Feature flags + experiment configuration for TV UI demo project", priority: "medium" },
  { title: "Performance Optimization Sprint", type: "project", roles: ["netflix-tvui-engineer", "anthropic-ui-engineer"], status: "not-started", desc: "Profile and optimize for constrained devices — FPS, memory, bundle size", priority: "high" },
  { title: "Netflix TVUI Architecture Deep Dive", type: "learning", roles: ["netflix-tvui-engineer"], status: "not-started", desc: "Custom renderer (Gibbon), React without DOM, spriting, focus management", priority: "high", hours: 6 },
  { title: "Netflix Culture Memo Study", type: "learning", roles: ["netflix-tvui-engineer"], status: "not-started", desc: "Read full Culture Memo, map values to personal stories, prep Dream Team round", priority: "high", hours: 4 },
  { title: "React Internals & Custom Renderers", type: "learning", roles: ["netflix-tvui-engineer", "anthropic-ui-engineer"], status: "not-started", desc: "React reconciler, custom renderers (react-three-fiber), lifecycle without DOM", priority: "medium", hours: 4 },
  { title: "TV Platform Coding Interview Prep", type: "learning", roles: ["netflix-tvui-engineer"], status: "not-started", desc: "LeetCode medium/hard in TypeScript, system design for CDN/streaming/recommendations", priority: "high", hours: 8 },
];

export const meta = {
  id: "netflix-tvui-engineer",
  company: "Netflix",
  title: "Software Engineer 4/5, TVUI",
  comp: "$388K–$558K",
  fit: "85%",
  priority: 8,
  status: "research",
  loc: "Remote (USA)",
  tags: ["IC","Frontend","React/TS","TV UI"],
  color: "#e50914",
  strengths: ["Direct TV UI experience at fuboTV","React/JS/TS depth","Shipped on constrained devices","Fully remote","Highest comp of all roles","Product-minded engineer"],
  gaps: [{g:"EM→IC transition narrative",s:"MEDIUM"},{g:"Netflix Gibbon renderer experience",s:"MEDIUM"},{g:"Recent hands-on IC velocity",s:"MEDIUM"},{g:"Performance profiling depth",s:"MEDIUM"}],
  verdict: "Possibly best overall fit. Direct TV UI experience + remote + highest comp.",
};

const S = [
  { id:"opp", title:"The Opportunity", icon:"◆", type:"opp", data:{
    role:"Software Engineer 4/5 — TVUI Engineering", comp:"$388K–$558K (salary + you choose stock/cash split)", team:"Member Engineering — TV User Interface", loc:"USA — Remote",
    focus:"Build the Netflix experience on hundreds of TV devices — from streaming sticks to smart TVs to game consoles. Three sub-tracks: Product Engineer (consumer features + A/B tests), Core Engineer (architecture + frameworks), Ads Engineer (ad platform + monetization). JavaScript/TypeScript, React, Redux — performance-obsessed for constrained devices.",
    whyNow:"Netflix is investing heavily in TV UI evolution. The TVUI codebase is React/TypeScript but runs on constrained devices (single-core smart TVs without JIT) using a custom rendering engine (no CSS, no mouse, no DOM). They run hundreds of A/B tests per year. The ads tier is a massive new revenue stream that needs engineering. And the team is distributed/remote-first — which works for you in Boca Raton.",
    status:"Active (posted Mar 3, 2026). Multiple roles across Product, Core, and Ads tracks. Open for at least 7 days, removed when filled.",
    verdict:"This might be the best overall fit across every role you've analyzed. Here's why: (1) You have DIRECT experience building TV UIs at fuboTV — Roku, Samsung, LG, Vizio, Apple TV. This is the exact same device ecosystem. (2) You know React/JavaScript/TypeScript deeply. (3) You shipped consumer features and performance improvements on constrained devices. (4) It's fully remote. (5) The comp ($388K-$558K) is the highest of any role you've looked at. (6) Netflix's 'freedom and responsibility' culture rewards self-directed, product-minded engineers — that's you. The EM→IC transition is the main friction, but your fuboTV IC experience (Senior SWE → EM → Director) means you've been a hands-on TV UI engineer before.",
  }},
  { id:"intel", title:"Company & Tech Intel", icon:"◇", type:"intel", data:{
    news:[
      {e:"Netflix TVUI runs React on non-web platforms", d:"Custom rendering engine called Gibbon (not DOM/CSS). React component model but renders to a canvas-like surface. No mouse, no CSS, custom focus management, spriting, styling solutions."},
      {e:"Constrained device challenge", d:"Single-core smart TVs running JSCore without JIT. Performance optimization is existential — every millisecond matters on low-powered devices. This is NOT standard web development."},
      {e:"Hundreds of A/B tests per year", d:"Netflix product engineering is driven by experimentation. Features are shipped as A/B tests, measured rigorously, and rolled out or killed based on data."},
      {e:"Ads tier is a major revenue initiative", d:"Netflix launched ads in 2022, now expanding with new formats, interactive ads, and server-side ad insertion. The Ads Engineer track is building this from the ground up on the TV platform."},
      {e:"Netflix culture: Freedom & Responsibility", d:"No vacation tracking, top-of-market pay, high expectations. 'Dream team' — high-caliber sports team, not a family. The Culture Memo is required reading for interviews."},
      {e:"Flexible comp: you choose salary vs stock split", d:"Netflix pays top-of-market. No bonuses. You decide what percentage is salary vs stock options. Plus 5% additional in stock options. They revise salaries annually based on market."},
    ],
    stack:[
      {name:"JavaScript / TypeScript", role:"Primary languages for the entire TVUI codebase", rel:"Core — must-have"},
      {name:"React", role:"Component model for TV UI (custom renderer, not ReactDOM)", rel:"Core — must-have"},
      {name:"Redux", role:"State management across the TV application", rel:"Core — must-have"},
      {name:"Gibbon (custom renderer)", role:"Netflix's proprietary rendering engine for TV — not CSS/DOM", rel:"Unique to Netflix"},
      {name:"Jest (proprietary variant)", role:"Testing framework — Netflix uses a custom Jest-based framework", rel:"Important"},
      {name:"A/B Testing Framework", role:"Experimentation platform for rapid feature testing", rel:"Core workflow"},
      {name:"Focus Management", role:"Custom keyboard navigation system (no mouse on TV)", rel:"Domain-specific"},
      {name:"Performance Profiling", role:"Critical for constrained devices — memory, CPU, rendering performance", rel:"Key skill"},
    ],
  }},
  { id:"fit", title:"Fit Analysis", icon:"△", type:"fit", data:{
    strengths:[
      "DIRECT TV UI experience at fuboTV — you built Roku, Samsung, LG, Vizio, and Apple TV apps. This is the SAME device ecosystem Netflix targets. Very few candidates have this background.",
      "JavaScript/TypeScript/React proficiency — the core tech stack matches. You've been writing JS for consumer platforms throughout your career.",
      "Performance optimization on constrained devices — at fuboTV you reduced crash rates from 13% to 0.1% on Roku. Netflix TVUI faces the same constrained-device challenges.",
      "Cross-platform shipping experience — you've shipped across Roku, SmartTV, Apple TV, mobile, web, and Quest OS. Netflix TVUI ships to hundreds of device types.",
      "Product-minded engineer — Netflix wants engineers who partner with designers and PMs, care about the user experience, and are curious about how members use the app. That's your natural mode.",
      "A/B testing and data-driven culture — you set KPIs/OKRs at fuboTV and worked with product on experimentation. Netflix runs hundreds of A/B tests per year.",
      "Fully remote — you're in Boca Raton. This role is explicitly remote-first with a distributed US team.",
      "IC engineering background — unlike the Anthropic PM roles, this leverages your actual engineering career path. You were a Senior SWE before becoming an EM.",
    ],
    adjacent:[
      "EM → IC transition: You've been managing for 4+ years. But unlike other IC roles you've looked at, this one directly maps to work you've DONE before as an IC at fuboTV. Your Roku/SmartTV code is basically the same problem domain.",
      "fuboTV → Netflix: Both are streaming platforms building TV UIs across the same device ecosystem. This is probably the most natural career move on your entire list.",
      "Quest OS Navigator → Netflix TVUI: Both are navigation-focused UIs for non-traditional platforms (VR headset vs Smart TV). Both require custom rendering, performance optimization, and novel interaction models.",
    ],
    gaps:[
      {gap:"4+ years since IC coding daily", critical:"MEDIUM", note:"You've been an EM at Meta since 2021. But your fuboTV IC work (2018-2020) was building exactly this kind of TV UI. The muscle memory is there — it needs refreshing, not rebuilding.", time:"2-3 weeks of focused coding practice"},
      {gap:"Netflix's custom rendering stack (Gibbon)", critical:"LOW", note:"Nobody outside Netflix knows Gibbon. They explicitly say 'Almost no one has a background in both JS and embedded devices, so we're happy to meet hungry learners.' Your TV platform background gives you the foundation they build on.", time:"Learn on the job — they expect this"},
      {gap:"Deep React internals knowledge", critical:"MEDIUM", note:"Netflix TVUI React is different from web React — custom renderer, no DOM, different lifecycle management. You know React well but may need to deepen your understanding of React's reconciler and custom renderers.", time:"2 weeks of deep React study"},
      {gap:"Netflix Culture Memo fluency", critical:"MEDIUM", note:"The behavioral interview at Netflix is famously make-or-break. You MUST read the Culture Memo thoroughly and prepare stories that map to their values. Candidates get rejected here even with strong technical performance.", time:"3-4 days of deep study + story prep"},
    ],
  }},
  { id:"knowledge", title:"Knowledge Map", icon:"▽", type:"knowledge", data:[
    {name:"Netflix TVUI Architecture", topics:["Gibbon: Netflix's custom React renderer for TV (no DOM, no CSS, canvas-like rendering)","Focus management: keyboard-driven navigation without a mouse","Spriting and custom styling: how Netflix handles visual layout without CSS","Performance on constrained devices: single-core CPUs, limited memory, no JIT compilation","React reconciler: how React works under the hood when you strip away the DOM","Device fragmentation: shipping to hundreds of different TV hardware/software combinations","A/B testing infrastructure: how experiments are configured, deployed, and measured on TV"], ai:"Ask Claude to explain how React works WITHOUT ReactDOM — what a custom renderer needs to implement. Then study how Netflix's Gibbon might work based on public blog posts and talks. Ask Claude to design a focus management system for TV navigation."},
    {name:"Performance Engineering for Constrained Devices", topics:["JavaScript performance on devices without JIT: what makes code slow on basic JSCore engines","Memory management in long-running applications (TV apps stay open for hours)","Rendering optimization: batching updates, minimizing repaints, efficient animations","Bundle size optimization: every KB matters on devices with limited storage","Profiling techniques: CPU flame charts, memory heap snapshots, rendering timelines","Cold start optimization: reducing time-to-interactive on slow TV hardware"], ai:"Ask Claude to walk through a performance optimization exercise: 'I have a React app running on a single-core Smart TV CPU with 512MB RAM and no JIT. It's janky when scrolling through a content row of 50 items. How do I fix it?' Practice thinking about performance from first principles."},
    {name:"React + TypeScript Deep Dive", topics:["React reconciliation algorithm: how React decides what to re-render","Custom React renderers: the HostConfig interface and what it requires","React Fiber architecture: how work is scheduled and prioritized","TypeScript strict mode: advanced types, generics, discriminated unions","Redux architecture: actions, reducers, middleware, selectors at scale","Testing patterns: unit testing React components, snapshot testing, integration tests with custom Jest"], ai:"Build a mini React application and profile it obsessively. Ask Claude to explain React Fiber's priority-based scheduling. Build a custom React renderer for a canvas element to understand how Netflix might approach Gibbon."},
    {name:"Netflix Culture & Interview Prep", topics:["Freedom & Responsibility: Netflix's core philosophy — high autonomy, high expectations","'Dream Team' concept: professional sports team, not a family. The 'keeper test'","Candor and feedback: radical honesty, giving and receiving tough feedback","Context not control: leaders provide context, teams make decisions","The culture interview: a director-level behavioral round that's uniquely intense","Behavioral stories to prepare: ownership without being asked, disagreeing then committing, handling ambiguity, giving hard feedback, making tradeoffs"], ai:"Read the Netflix Culture Memo end-to-end (jobs.netflix.com/culture). Then ask Claude to run mock culture interviews with you. Practice 10 STAR stories that map to Netflix values. This is NOT optional — failing the behavioral round is the #1 reason strong engineers get rejected at Netflix."},
    {name:"Streaming Platform Domain", topics:["Content delivery: how video gets from Netflix's servers to the TV (CDN, adaptive bitrate)","Personalization: how the recommendation engine drives what you see on the home screen","Engagement metrics: what Netflix measures and optimizes for (viewing hours, retention, session length)","Ads platform: server-side ad insertion, ad formats, targeting on connected TV","The member experience funnel: browse → select → play → continue watching"], ai:"Use Netflix daily and study every UI interaction on a TV. Ask Claude: 'Design the architecture for Netflix's home screen content loading on a Smart TV with 512MB RAM. How do you handle personalized rows, image loading, and smooth scrolling?'"},
    {name:"Coding Interview Prep", topics:["Medium/hard LeetCode: focus on data structures, arrays, trees, graphs, dynamic programming","Real-world problems: in-memory file systems, data parsing, streaming metrics processing","System design: Netflix video streaming CDN, recommendation system, A/B testing platform","Code quality: clean code, good naming, proper error handling, testability","Communication during coding: think out loud, discuss tradeoffs, explain decisions"], ai:"Practice 2 LeetCode problems daily in TypeScript. Focus on clean, well-structured solutions over speed. Netflix values code quality and communication over raw speed. Ask Claude to play Netflix interviewer and evaluate your code on readability, edge cases, and tradeoff discussion."},
  ]},
  { id:"plan", title:"30-Day Sprint", icon:"⬡", type:"plan", data:[
    {week:"Week 1: Refresh TV UI Engineering Skills", days:[
      {day:"Days 1-2", focus:"React + TypeScript Deep Refresh", tasks:["Build a complex React component with TypeScript strict mode — a scrollable content grid with keyboard navigation (no mouse)","Implement custom focus management: arrow keys navigate between items, Enter selects","Profile with React DevTools — identify unnecessary re-renders and optimize","This recreates the core Netflix TVUI interaction model"], hrs:"4-5 hrs/day"},
      {day:"Days 3-4", focus:"Performance on Constrained Devices", tasks:["Study: how does JavaScript perform without JIT compilation? What patterns are slow?","Build a content row that virtualized renders (only visible items in DOM/canvas)","Optimize: reduce bundle size, lazy load images, implement efficient scrolling","Benchmark: measure FPS, memory usage, time-to-interactive. Document improvements."], hrs:"4-5 hrs/day"},
      {day:"Days 5-6", focus:"TV Platform Portfolio Project", tasks:["Build a Netflix-style content browser using React + TypeScript","Keyboard-only navigation, content rows, hero banners, smooth animations","Focus management: arrow keys, Enter to select, Back to go up a level","Make it feel like a TV app — big text, 10-foot UI design principles, no mouse interactions"], hrs:"4-5 hrs/day"},
      {day:"Day 7", focus:"Synthesis", tasks:["Deploy your TV UI demo. Write a README explaining architecture decisions.","Document every performance optimization with before/after metrics."], hrs:"2-3 hrs"},
    ]},
    {week:"Week 2: Netflix Deep Dive + Culture Prep", days:[
      {day:"Days 8-9", focus:"Netflix Culture Memo + Behavioral Prep", tasks:["Read the Netflix Culture Memo THOROUGHLY (jobs.netflix.com/culture)","Write down every value and principle. Map each one to a personal story.","Prepare 10 STAR stories: ownership, feedback, ambiguity, disagreement, tradeoffs","Practice the 'Dream Team' behavioral round with Claude as interviewer"], hrs:"4-5 hrs/day"},
      {day:"Days 10-11", focus:"Netflix TVUI Technical Deep Dive", tasks:["Read Netflix Tech Blog posts about TVUI architecture","Study how React renders without DOM — research custom React renderers","Understand the unique challenges: no CSS, no mouse, spriting, focus management","Watch any available Netflix tech talks on TVUI engineering (YouTube/conferences)"], hrs:"3-4 hrs/day"},
      {day:"Days 12-13", focus:"A/B Testing + Product Thinking", tasks:["Study Netflix's experimentation culture — how they run hundreds of A/B tests per year","Build a simple A/B testing framework in your TV UI demo project","Practice: 'How would you design an A/B test for a new Netflix browse experience?'","Study engagement metrics: what makes a TV UI 'successful' at Netflix?"], hrs:"3-4 hrs/day"},
      {day:"Day 14", focus:"Synthesis", tasks:["Review: can you explain Netflix TVUI architecture to an interviewer?","Review: do you have 10 strong STAR stories mapped to Netflix values?","Review: is your TV UI portfolio project polished and deployed?"], hrs:"2-3 hrs"},
    ]},
    {week:"Week 3: Coding + System Design Prep", days:[
      {day:"Days 15-17", focus:"LeetCode + Coding Practice", tasks:["2 problems per day in TypeScript — medium difficulty, focus on quality over speed","Practice real-world problems: in-memory file systems, log parsing, data transformers","Practice live coding with Claude as the interviewer — think out loud, discuss tradeoffs","Focus areas: arrays, trees, hash maps, string manipulation, dynamic programming"], hrs:"3-4 hrs/day"},
      {day:"Days 18-19", focus:"System Design Practice", tasks:["Design: Netflix content delivery + adaptive bitrate streaming architecture","Design: Netflix recommendation system for the TV home screen","Design: A/B testing platform that serves experiments to hundreds of device types","Design: server-side ad insertion architecture for connected TV","Practice explaining designs at both high level (VP audience) and deep level (peer engineer)"], hrs:"3-4 hrs/day"},
      {day:"Days 20-21", focus:"Full Mock Interviews", tasks:["Mock 1: coding round (2 problems, 50 min each)","Mock 2: system design (Netflix-specific, 75 min)","Mock 3: culture fit / Dream Team round (45 min with Claude as Netflix director)","Identify weak areas and drill them"], hrs:"4-5 hrs/day"},
    ]},
    {week:"Week 4: Apply + Final Prep", days:[
      {day:"Days 22-25", focus:"Application Materials + Track Selection", tasks:["Decide which track: Product Engineer, Core Engineer, or Ads Engineer","Product = best fit (consumer features, cross-functional, A/B tests — your wheelhouse)","Resume: lead with fuboTV TV UI experience, then Meta, emphasize React/TS/performance","Cover letter: connect fuboTV TV platform → Meta Quest OS → Netflix TVUI narrative","Include link to your TV UI portfolio project"], hrs:"3-4 hrs/day"},
      {day:"Days 26-28", focus:"Final Mock Loop + Polish", tasks:["Full mock interview day: recruiter screen + coding + system design + culture fit","Refine behavioral stories based on mock feedback","Review Netflix culture memo one more time — internalize, don't memorize","Prepare 5 thoughtful questions to ask interviewers about the TVUI team"], hrs:"4-5 hrs/day"},
      {day:"Days 29-30", focus:"Submit + Network", tasks:["Submit application to Netflix TVUI Engineering","Reach out to Netflix TVUI engineers on LinkedIn — ask about the team culture","Post about your TV UI demo project on Twitter","Follow up on all other applications in progress"], hrs:"2-3 hrs/day"},
    ]},
  ]},
  { id:"tactics", title:"AI Tactics", icon:"□", type:"tactics", data:[
    {name:"Claude as TV UI Architecture Tutor", desc:"Deep dive into how React can render without a DOM — the core Netflix TVUI concept.", ex:"Explain how Netflix's TVUI works. They use React but not ReactDOM — there's no CSS, no mouse, no standard DOM. How does React render to a custom surface like a canvas? Walk me through building a custom React renderer and a keyboard-based focus management system."},
    {name:"Claude as Netflix Culture Coach", desc:"Practice the notoriously intense Netflix behavioral interview.", ex:"You're a Netflix Engineering Director conducting the 'Dream Team' interview. Grill me on: a time I took ownership without being asked, how I handle radical candor and tough feedback, a decision I made with incomplete information, and why I'd thrive in Netflix's 'freedom and responsibility' culture. Be intense — Netflix rejects strong engineers who fail this round."},
    {name:"Claude as Performance Optimization Partner", desc:"Practice the constrained-device performance thinking Netflix TVUI demands.", ex:"I have a React content grid running on a Smart TV with a single-core CPU, 512MB RAM, and a JavaScript engine without JIT compilation. Scrolling through 200 content tiles is janky at 12fps. Walk me through every optimization I should consider: rendering, memory, bundle size, virtualization, image loading, animation strategy. I need to hit 60fps."},
    {name:"Claude as System Design Interviewer", desc:"Practice Netflix-specific system design questions.", ex:"You're a Netflix TVUI architect. Ask me to design the Netflix TV home screen loading experience for a low-end Smart TV. It needs to: load personalized content rows from the API, render hero artwork, support keyboard navigation, handle offline/slow network gracefully, and support A/B tests on row ordering. Evaluate my design."},
    {name:"Claude as Coding Interview Partner", desc:"Practice clean, communicative coding in TypeScript.", ex:"Give me a Netflix-style coding problem. Not a pure LeetCode puzzle — something that mirrors real work. Maybe parsing streaming metrics data, building a content cache with eviction, or implementing a priority queue for content loading. Evaluate me on: code quality, edge case handling, tradeoff discussion, and how clearly I communicate my thinking."},
  ]},
  { id:"res", title:"Resources", icon:"◈", type:"res", data:[
    {cat:"Must Read (Do These First)", items:["Netflix Culture Memo (jobs.netflix.com/culture) — READ THE WHOLE THING","Netflix Tech Blog: 'Crafting a High-Performance TV User Interface Using React'","Blind thread: 'What is it like on the Netflix TV UI Team?' (real engineer answers)","Netflix Tech Blog: all TVUI-related posts"]},
    {cat:"Technical Depth", items:["React reconciliation algorithm deep dive","Custom React renderers: react-three-fiber source code as a reference","JavaScript performance on constrained devices (no JIT engines)","Redux best practices for large-scale applications","10-foot UI design principles (TV interface design patterns)"]},
    {cat:"Interview Prep", items:["interviewing.io Netflix guide — real candidate experiences","LeetCode medium/hard in TypeScript (2 per day)","System Design Primer (GitHub) — focus on CDN, streaming, recommendations","Prepfully Netflix SWE guide — round-by-round breakdown","Netflix open-source projects: Hystrix, Eureka, Zuul (understand the culture of OSS)"]},
    {cat:"Build", items:["TV UI portfolio project: React + TypeScript content browser with keyboard nav","Performance profiling: Chrome DevTools, React Profiler","A/B testing framework: feature flags + experiment configuration","Focus management system: arrow-key navigation without mouse"]},
  ]},
];

const Badge = ({color,children}) => {
  const c = {green:"bg-emerald-500/15 text-emerald-300 border-emerald-500/30",amber:"bg-amber-500/15 text-amber-300 border-amber-500/30",red:"bg-red-500/15 text-red-300 border-red-500/30",blue:"bg-blue-500/15 text-blue-300 border-blue-500/30",gray:"bg-gray-500/15 text-gray-300 border-gray-500/30"};
  return <span className={`text-xs px-2 py-0.5 rounded-full border font-mono ${c[color]}`}>{children}</span>;
};
const Opp = ({d}) => (<div className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[["ROLE",d.role],["COMP",d.comp],["TEAM",d.team],["LOCATION",d.loc]].map(([l,v])=><div key={l} className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">{l}</div><div className="text-white text-sm">{v}</div></div>)}</div><div className="bg-white/5 border border-white/10 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">FOCUS</div><div className="text-white text-sm">{d.focus}</div></div><div className="bg-emerald-900/20 border border-emerald-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-400 mb-1.5 font-mono">WHY NOW</div><div className="text-emerald-200 text-sm leading-relaxed">{d.whyNow}</div></div><div className="bg-amber-900/20 border border-amber-600/30 rounded-lg p-4"><div className="text-xs tracking-widest text-amber-400 mb-1.5 font-mono">STATUS</div><div className="text-amber-200 text-sm">{d.status}</div></div><div className="bg-emerald-900/30 border border-emerald-400/40 rounded-lg p-4"><div className="text-xs tracking-widest text-emerald-300 mb-1.5 font-mono">BOTTOM LINE</div><div className="text-emerald-100 text-sm font-medium">{d.verdict}</div></div></div>);
const Intel = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">KEY CONTEXT</div>{d.news.map((n,i)=><div key={i} className="bg-white/5 border border-white/10 rounded-lg p-3 mb-2"><div className="text-white text-sm font-medium mb-1">{n.e}</div><div className="text-gray-400 text-sm">{n.d}</div></div>)}</div><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">TECH STACK</div>{d.stack.map((s,i)=><div key={i} className="flex items-center gap-3 py-1.5"><Badge color={s.rel.includes("Core")?"green":s.rel.includes("Unique")?"amber":s.rel.includes("Key")?"blue":"gray"}>{s.rel}</Badge><span className="text-white text-sm font-medium min-w-36">{s.name}</span><span className="text-gray-500 text-sm">{s.role}</span></div>)}</div></div>);
const FitView = ({d}) => (<div className="space-y-6"><div><div className="text-xs tracking-widest text-emerald-400 mb-3 font-mono">STRENGTHS — THIS IS YOUR STRONGEST IC FIT</div>{d.strengths.map((s,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-emerald-400 mt-0.5 text-xs">✓</span><span className="text-gray-300 text-sm">{s}</span></div>)}</div><div><div className="text-xs tracking-widest text-blue-400 mb-3 font-mono">ADJACENT — NATURAL CAREER ARC</div>{d.adjacent.map((a,i)=><div key={i} className="flex items-start gap-2 mb-2"><span className="text-blue-400 mt-0.5 text-xs">↗</span><span className="text-gray-300 text-sm">{a}</span></div>)}</div><div><div className="text-xs tracking-widest text-amber-400 mb-3 font-mono">GAPS — ALL MANAGEABLE</div>{d.gaps.map((g,i)=><div key={i} className="border border-white/10 rounded-lg p-3 mb-2"><div className="flex items-center gap-2 mb-1"><span className="text-white text-sm font-medium">{g.gap}</span><Badge color={g.critical==="LOW"?"green":"amber"}>{g.critical}</Badge></div><p className="text-gray-400 text-sm">{g.note}</p><div className="text-xs text-gray-600 font-mono mt-1">Close in: {g.time}</div></div>)}</div></div>);
const KMap = ({d}) => {const [exp,setExp]=useState(null);return <div className="space-y-2">{d.map((k,i)=><div key={i} className="border border-white/10 rounded-lg overflow-hidden"><button onClick={()=>setExp(exp===i?null:i)} className="w-full text-left p-4 flex items-center justify-between hover:bg-white/5 transition-colors"><span className="text-white font-medium text-sm">{k.name}</span><span className="text-gray-500">{exp===i?"−":"+"}</span></button>{exp===i&&<div className="px-4 pb-4 border-t border-white/5"><div className="mt-3 space-y-1.5">{k.topics.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-amber-400 mt-1 text-xs">›</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div><div className="mt-3 bg-blue-900/20 border border-blue-500/20 rounded-lg p-3"><div className="text-xs tracking-widest text-blue-400 mb-1 font-mono">AI ACCELERATION</div><p className="text-blue-200 text-sm">{k.ai}</p></div></div>}</div>)}</div>};
const Plan = ({d}) => {const [aw,setAw]=useState(0);const w=d[aw];return <div><div className="flex gap-2 mb-4 overflow-x-auto">{d.map((_,i)=><button key={i} onClick={()=>setAw(i)} className={`px-3 py-1.5 rounded-lg text-xs font-mono whitespace-nowrap transition-all ${aw===i?"bg-amber-500/20 text-amber-300 border border-amber-500/40":"bg-white/5 text-gray-400 border border-white/10"}`}>Wk {i+1}</button>)}</div><h4 className="text-white font-medium mb-4">{w.week}</h4><div className="space-y-4">{w.days.map((d,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="flex items-center justify-between mb-3"><div><span className="text-amber-400 font-mono text-xs">{d.day}</span><span className="text-gray-500 mx-2">·</span><span className="text-white text-sm font-medium">{d.focus}</span></div><span className="text-gray-600 text-xs font-mono">{d.hrs}</span></div><div className="space-y-1.5">{d.tasks.map((t,j)=><div key={j} className="flex items-start gap-2"><span className="text-gray-600 mt-0.5 text-xs font-mono">{String(j+1).padStart(2,"0")}</span><span className="text-gray-300 text-sm">{t}</span></div>)}</div></div>)}</div></div>};
const Tactics = ({d}) => <div className="space-y-4">{d.map((t,i)=><div key={i} className="border border-white/10 rounded-lg p-4"><div className="text-white font-medium text-sm mb-1">{t.name}</div><p className="text-gray-400 text-sm mb-3">{t.desc}</p><div className="bg-gray-900 rounded-lg p-3 border border-white/5"><div className="text-xs text-gray-600 font-mono mb-1">PROMPT</div><p className="text-amber-300 text-sm italic">"{t.ex}"</p></div></div>)}</div>;
const Res = ({d}) => <div className="space-y-6">{d.map((c,i)=><div key={i}><div className="text-xs tracking-widest text-amber-400 mb-2 font-mono">{c.cat.toUpperCase()}</div>{c.items.map((item,j)=><div key={j} className="flex items-start gap-2 mb-1"><span className="text-gray-600 mt-0.5 text-xs">›</span><span className="text-gray-300 text-sm">{item}</span></div>)}</div>)}</div>;
const R = {opp:Opp,intel:Intel,fit:FitView,knowledge:KMap,plan:Plan,tactics:Tactics,res:Res};

export default function Brief() {
  const [a,setA] = useState("opp");
  const s = S.find(x=>x.id===a);
  const V = R[s.type];
  return (
    <div className="min-h-screen text-white" style={{background:"linear-gradient(160deg,#090909 0%,#0e0e0e 50%,#0a0a0a 100%)",fontFamily:"'IBM Plex Sans',sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap');.font-mono{font-family:'IBM Plex Mono',monospace}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.1);border-radius:2px}`}</style>
      <div className="border-b border-white/10 px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-3"><div className="w-2 h-2 bg-emerald-400 rounded-full animate-pulse"/><span className="text-xs font-mono text-gray-500 tracking-widest">JOB PREP INTELLIGENCE BRIEF — HIGH PRIORITY</span></div><h1 className="text-2xl md:text-3xl font-light text-white mb-2" style={{letterSpacing:"-0.02em"}}>Netflix · TVUI Software Engineer</h1><p className="text-gray-500 text-sm">Your fuboTV experience was training for this · Remote · $388K-$558K · 30-day sprint</p></div></div>
      <div className="border-b border-white/10 px-6 py-3 sticky top-0 z-10" style={{background:"rgba(9,9,9,0.95)",backdropFilter:"blur(12px)"}}><div className="max-w-4xl mx-auto flex gap-1 overflow-x-auto">{S.map(x=><button key={x.id} onClick={()=>setA(x.id)} className={`px-3 py-1.5 rounded-md text-xs font-mono whitespace-nowrap transition-all ${a===x.id?"bg-white/10 text-white":"text-gray-600 hover:text-gray-400"}`}><span className="mr-1.5">{x.icon}</span>{x.title}</button>)}</div></div>
      <div className="px-6 py-8"><div className="max-w-4xl mx-auto"><div className="flex items-center gap-2 mb-6"><span className="text-amber-400 text-lg">{s.icon}</span><h2 className="text-xl font-light text-white">{s.title}</h2></div><V d={s.data}/></div></div>
      <div className="border-t border-white/5 px-6 py-4"><div className="max-w-4xl mx-auto text-center"><p className="text-gray-700 text-xs font-mono">~100 hrs over 30 days · refresh existing skills, not learn new ones · culture prep is critical</p></div></div>
    </div>
  );
}
